// Mocks generated by Mockito 5.4.6 from annotations
// in cente_pice/test/unit/features/parts/data/repositories/user_settings_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cente_pice/src/core/network/network_info.dart' as _i5;
import 'package:cente_pice/src/features/parts/data/datasources/user_settings_remote_datasource.dart'
    as _i3;
import 'package:cente_pice/src/features/parts/data/models/user_settings_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserSettingsModel_0 extends _i1.SmartFake
    implements _i2.UserSettingsModel {
  _FakeUserSettingsModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserSettingsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSettingsRemoteDataSource extends _i1.Mock
    implements _i3.UserSettingsRemoteDataSource {
  MockUserSettingsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserSettingsModel?> getUserSettings(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserSettings,
          [userId],
        ),
        returnValue: _i4.Future<_i2.UserSettingsModel?>.value(),
      ) as _i4.Future<_i2.UserSettingsModel?>);

  @override
  _i4.Future<_i2.UserSettingsModel> saveUserSettings(
          _i2.UserSettingsModel? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserSettings,
          [settings],
        ),
        returnValue:
            _i4.Future<_i2.UserSettingsModel>.value(_FakeUserSettingsModel_0(
          this,
          Invocation.method(
            #saveUserSettings,
            [settings],
          ),
        )),
      ) as _i4.Future<_i2.UserSettingsModel>);

  @override
  _i4.Future<void> deleteUserSettings(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteUserSettings,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
