// Mocks generated by Mockito 5.4.6 from annotations
// in cente_pice/test/unit/features/auth/presentation/controllers/particulier_auth_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cente_pice/src/core/errors/failures.dart' as _i6;
import 'package:cente_pice/src/core/usecases/usecase.dart' as _i8;
import 'package:cente_pice/src/features/auth/domain/entities/particulier.dart'
    as _i7;
import 'package:cente_pice/src/features/auth/domain/repositories/particulier_auth_repository.dart'
    as _i2;
import 'package:cente_pice/src/features/auth/domain/usecases/get_current_particulier.dart'
    as _i10;
import 'package:cente_pice/src/features/auth/domain/usecases/particulier_anonymous_auth.dart'
    as _i4;
import 'package:cente_pice/src/features/auth/domain/usecases/particulier_logout.dart'
    as _i9;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeParticulierAuthRepository_0 extends _i1.SmartFake
    implements _i2.ParticulierAuthRepository {
  _FakeParticulierAuthRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ParticulierAnonymousAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockParticulierAnonymousAuth extends _i1.Mock
    implements _i4.ParticulierAnonymousAuth {
  MockParticulierAnonymousAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ParticulierAuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeParticulierAuthRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ParticulierAuthRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Particulier>> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Particulier>>.value(
            _FakeEither_1<_i6.Failure, _i7.Particulier>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Particulier>>);
}

/// A class which mocks [ParticulierLogout].
///
/// See the documentation for Mockito's code generation for more information.
class MockParticulierLogout extends _i1.Mock implements _i9.ParticulierLogout {
  MockParticulierLogout() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ParticulierAuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeParticulierAuthRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ParticulierAuthRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [GetCurrentParticulier].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentParticulier extends _i1.Mock
    implements _i10.GetCurrentParticulier {
  MockGetCurrentParticulier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ParticulierAuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeParticulierAuthRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ParticulierAuthRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Particulier>> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Particulier>>.value(
            _FakeEither_1<_i6.Failure, _i7.Particulier>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Particulier>>);
}
