name: 🚀 Feature Request
description: Proposer une nouvelle fonctionnalité
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Merci de proposer cette amélioration ! Décrivez votre idée ci-dessous.

  - type: dropdown
    id: type
    attributes:
      label: 🎯 Type de fonctionnalité
      description: Quel type de fonctionnalité proposez-vous ?
      options:
        - Nouvelle page/écran
        - Amélioration UX/UI
        - Nouvelle API/intégration
        - Optimisation performance
        - Fonctionnalité business
        - Outil développeur
        - Autre
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Priorité
      description: Quelle priorité pour cette fonctionnalité ?
      options:
        - Critique (bloquant business)
        - Haute (très important)
        - Moyenne (amélioration notable)
        - Basse (nice to have)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 🚨 Problème à résoudre
      description: Quel problème cette fonctionnalité résout-elle ?
      placeholder: "Les utilisateurs ne peuvent pas..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Solution proposée
      description: Décrivez la solution que vous envisagez
      placeholder: "Je propose d'ajouter..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives considérées
      description: Avez-vous pensé à d'autres solutions ?

  - type: textarea
    id: user_story
    attributes:
      label: 👤 User Story
      description: Décrivez du point de vue utilisateur
      placeholder: "En tant que [utilisateur], je veux [faire quelque chose] afin de [atteindre un objectif]"

  - type: textarea
    id: acceptance
    attributes:
      label: ✅ Critères d'acceptation
      description: Comment saurez-vous que c'est terminé ?
      placeholder: |
        - [ ] L'utilisateur peut...
        - [ ] Le système affiche...
        - [ ] La performance est...

  - type: textarea
    id: mockups
    attributes:
      label: 🎨 Mockups/Wireframes
      description: Ajoutez des designs ou croquis si applicable

  - type: dropdown
    id: platforms
    attributes:
      label: 📱 Plateformes concernées
      description: Quelles plateformes sont concernées ?
      multiple: true
      options:
        - Android
        - iOS
        - Web
        - Backend
        - Toutes

  - type: input
    id: effort
    attributes:
      label: ⏱️ Estimation effort
      description: Estimation développement (jours/semaines)
      placeholder: "2-3 jours, 1 semaine, etc."

  - type: textarea
    id: impact
    attributes:
      label: 📈 Impact métier
      description: Quel sera l'impact business ?
      placeholder: "Augmentation engagement, réduction churn, etc."

  - type: textarea
    id: dependencies
    attributes:
      label: 🔗 Dépendances
      description: Cette fonctionnalité dépend-elle d'autre chose ?

  - type: textarea
    id: additional
    attributes:
      label: 📋 Informations supplémentaires
      description: Autres détails utiles

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Checklist
      description: Vérifiez les éléments suivants
      options:
        - label: J'ai cherché si cette fonctionnalité a déjà été proposée
          required: true
        - label: J'ai défini des critères d'acceptation clairs
          required: true
        - label: Cette fonctionnalité apporte une vraie valeur utilisateur
          required: true