class CarPartsList {
  static const List<String> allParts = [
    // Moteur
    'Moteur',
    'Bloc moteur',
    'Culasse',
    'Vilebrequin',
    'Bielles',
    'Pistons',
    'Segments',
    'Soupapes',
    'Arbre à cames',
    'Courroie de distribution',
    'Chaîne de distribution',
    'Pompe à eau',
    'Thermostat',
    'Radiateur',
    'Ventilateur de refroidissement',
    'Durite de refroidissement',
    'Réservoir expansion',
    'Pompe à huile',
    'Carter d\'huile',
    'Joint de culasse',
    'Joint d\'étanchéité',
    'Filtre à huile',
    'Filtre à air',
    'Filtre à carburant',
    'Injecteur',
    'Pompe à injection',
    'Turbocompresseur',
    'Compresseur',
    'Intercooler',
    'Collecteur d\'admission',
    'Collecteur d\'échappement',
    'Catalyseur',
    'Pot d\'échappement',
    'Silencieux',
    'Ligne d\'échappement',
    'Sonde lambda',
    'Bobine d\'allumage',
    'Bougie d\'allumage',
    'Bougie de préchauffage',
    'Alternateur',
    'Démarreur',
    'Batterie',
    'Courroie accessoire',
    'Poulie',
    'Galet tendeur',
    'Support moteur',

    // Transmission
    'Boîte de vitesses',
    'Embrayage',
    'Disque d\'embrayage',
    'Mécanisme d\'embrayage',
    'Butée d\'embrayage',
    'Volant moteur',
    'Arbre de transmission',
    'Cardan',
    'Joint de cardan',
    'Différentiel',
    'Pont',
    'Demi-train',
    'Soufflet de cardan',

    // Freinage
    'Plaquettes de frein',
    'Disque de frein',
    'Tambour de frein',
    'Mâchoires de frein',
    'Étrier de frein',
    'Maître-cylindre',
    'Cylindre de roue',
    'Servo-frein',
    'ABS',
    'Capteur ABS',
    'Liquide de frein',
    'Flexible de frein',
    'Frein à main',
    'Câble de frein à main',

    // Direction
    'Volant',
    'Colonne de direction',
    'Crémaillère',
    'Boîtier de direction',
    'Biellette de direction',
    'Rotule de direction',
    'Soufflet de crémaillère',
    'Pompe de direction assistée',
    'Réservoir LDR',
    'Liquide de direction',

    // Suspension
    'Amortisseur',
    'Ressort',
    'Coupelle d\'amortisseur',
    'Butée de compression',
    'Bras de suspension',
    'Triangle de suspension',
    'Silent-bloc',
    'Rotule de suspension',
    'Barre stabilisatrice',
    'Biellette de barre stabilisatrice',
    'Jambe de force',
    'Combiné fileté',

    // Roues et pneus
    'Jante',
    'Pneu',
    'Chambre à air',
    'Valve',
    'Enjoliveur',
    'Cache moyeu',
    'Écrou de roue',
    'Boulon de roue',
    'Roulement de roue',
    'Moyeu',

    // Carrosserie
    'Pare-chocs avant',
    'Pare-chocs arrière',
    'Aile avant',
    'Aile arrière',
    'Portière',
    'Capot',
    'Coffre',
    'Hayon',
    'Toit ouvrant',
    'Becquet',
    'Spoiler',
    'Calandre',
    'Grille de radiateur',
    'Rétroviseur',
    'Coque de rétroviseur',
    'Glace de rétroviseur',
    'Vitre avant',
    'Vitre arrière',
    'Vitre latérale',
    'Pare-brise',
    'Lunette arrière',
    'Joint de vitre',
    'Mécanisme lève-vitre',
    'Poignée de portière',
    'Serrure de portière',
    'Barillet de serrure',
    'Cylindre de serrure',

    // Éclairage
    'Phare avant',
    'Feu arrière',
    'Clignotant',
    'Feu de brouillard',
    'Feu de recul',
    'Feu stop',
    'Veilleuse',
    'Ampoule',
    'LED',
    'Xenon',
    'Projecteur',
    'Réflecteur',
    'Optique',

    // Intérieur
    'Siège avant',
    'Siège arrière',
    'Banquette',
    'Appui-tête',
    'Ceinture de sécurité',
    'Enrouleur de ceinture',
    'Tableau de bord',
    'Compteur',
    'Combiné d\'instruments',
    'Autoradio',
    'GPS',
    'Écran multimédia',
    'Haut-parleur',
    'Antenne',
    'Console centrale',
    'Boîte à gants',
    'Vide-poches',
    'Tapis de sol',
    'Moquette',
    'Garniture de portière',
    'Poignée intérieure',
    'Commutateur',
    'Bouton',
    'Manette',
    'Levier de vitesse',
    'Pommeau de levier',
    'Frein à main',
    'Pédale',
    'Accélérateur',
    'Embrayage',
    'Frein',

    // Climatisation
    'Compresseur de climatisation',
    'Condenseur',
    'Évaporateur',
    'Détendeur',
    'Filtre déshydratant',
    'Flexible de climatisation',
    'Gaz réfrigérant',
    'Ventilateur d\'habitacle',
    'Pulseur d\'air',
    'Résistance de chauffage',
    'Radiateur de chauffage',
    'Filtre d\'habitacle',
    'Bouche d\'aération',
    'Grille d\'aération',

    // Électronique
    'Calculateur',
    'ECU',
    'BCM',
    'Faisceau électrique',
    'Connecteur',
    'Fusible',
    'Relais',
    'Capteur',
    'Sonde',
    'Actionneur',
    'Moteur électrique',
    'Centrale clignotante',
    'Régulateur de tension',
    'Commande électronique',

    // Accessoires
    'Essuie-glace',
    'Balai d\'essuie-glace',
    'Moteur d\'essuie-glace',
    'Pompe de lave-glace',
    'Réservoir lave-glace',
    'Gicleur',
    'Klaxon',
    'Avertisseur sonore',
    'Rétroviseur intérieur',
    'Pare-soleil',
    'Plafonnier',
    'Éclairage intérieur',
    'Prise 12V',
    'Allume-cigare',
    'Cendrier',
    'Attelage',
    'Crochet d\'attelage',
    'Faisceau d\'attelage',
    'Galerie de toit',
    'Barres de toit',
  ];

  static List<String> searchParts(String query) {
    if (query.isEmpty) return [];
    
    final lowercaseQuery = query.toLowerCase();
    return allParts
        .where((part) => part.toLowerCase().contains(lowercaseQuery))
        .take(8) // Limite à 8 suggestions
        .toList();
  }
}