// Mocks generated by Mockito 5.4.6 from annotations
// in cente_pice/test/unit/features/parts/presentation/controllers/part_advertisement_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cente_pice/src/core/errors/failures.dart' as _i5;
import 'package:cente_pice/src/features/parts/data/models/part_advertisement_model.dart'
    as _i7;
import 'package:cente_pice/src/features/parts/domain/entities/part_advertisement.dart'
    as _i6;
import 'package:cente_pice/src/features/parts/domain/repositories/part_advertisement_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PartAdvertisementRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPartAdvertisementRepository extends _i1.Mock
    implements _i3.PartAdvertisementRepository {
  MockPartAdvertisementRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i6.PartAdvertisement>> createPartAdvertisement(
          _i7.CreatePartAdvertisementParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPartAdvertisement,
          [params],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.PartAdvertisement>>.value(
                _FakeEither_0<_i5.Failure, _i6.PartAdvertisement>(
          this,
          Invocation.method(
            #createPartAdvertisement,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.PartAdvertisement>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PartAdvertisement>>
      getPartAdvertisementById(String? id) => (super.noSuchMethod(
            Invocation.method(
              #getPartAdvertisementById,
              [id],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, _i6.PartAdvertisement>>.value(
                _FakeEither_0<_i5.Failure, _i6.PartAdvertisement>(
              this,
              Invocation.method(
                #getPartAdvertisementById,
                [id],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.PartAdvertisement>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PartAdvertisement>>>
      getMyPartAdvertisements({String? particulierId}) => (super.noSuchMethod(
            Invocation.method(
              #getMyPartAdvertisements,
              [],
              {#particulierId: particulierId},
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.PartAdvertisement>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.PartAdvertisement>>(
              this,
              Invocation.method(
                #getMyPartAdvertisements,
                [],
                {#particulierId: particulierId},
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i6.PartAdvertisement>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.PartAdvertisement>>>
      searchPartAdvertisements(_i7.SearchPartAdvertisementsParams? params) =>
          (super.noSuchMethod(
            Invocation.method(
              #searchPartAdvertisements,
              [params],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.PartAdvertisement>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.PartAdvertisement>>(
              this,
              Invocation.method(
                #searchPartAdvertisements,
                [params],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i6.PartAdvertisement>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i6.PartAdvertisement>> updatePartAdvertisement(
    String? id,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePartAdvertisement,
          [
            id,
            updates,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.PartAdvertisement>>.value(
                _FakeEither_0<_i5.Failure, _i6.PartAdvertisement>(
          this,
          Invocation.method(
            #updatePartAdvertisement,
            [
              id,
              updates,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.PartAdvertisement>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deletePartAdvertisement(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePartAdvertisement,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deletePartAdvertisement,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> markAsSold(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsSold,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #markAsSold,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> incrementViewCount(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementViewCount,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #incrementViewCount,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> incrementContactCount(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementContactCount,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #incrementContactCount,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
