import 'package:freezed_annotation/freezed_annotation.dart';

part 'seller_rejection.freezed.dart';

@freezed
class SellerRejection with _$SellerRejection {
  const factory SellerRejection({
    required String id,
    required String sellerId,
    required String partRequestId,
    required DateTime rejectedAt,
    String? reason,
    required DateTime createdAt,
    required DateTime updatedAt,
  }) = _SellerRejection;

  factory SellerRejection.create({
    required String sellerId,
    required String partRequestId,
    String? reason,
  }) {
    final now = DateTime.now();
    return SellerRejection(
      id: '', // Will be generated by database
      sellerId: sellerId,
      partRequestId: partRequestId,
      rejectedAt: now,
      reason: reason,
      createdAt: now,
      updatedAt: now,
    );
  }
}
