// Mocks generated by Mockito 5.4.6 from annotations
// in cente_pice/test/unit/features/auth/domain/usecases/seller_login_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cente_pice/src/core/errors/failures.dart' as _i5;
import 'package:cente_pice/src/features/auth/domain/entities/seller.dart'
    as _i6;
import 'package:cente_pice/src/features/auth/domain/repositories/seller_auth_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SellerAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSellerAuthRepository extends _i1.Mock
    implements _i3.SellerAuthRepository {
  MockSellerAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Seller>> registerSeller({
    required String? email,
    required String? password,
    String? firstName,
    String? lastName,
    String? companyName,
    String? phone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerSeller,
          [],
          {
            #email: email,
            #password: password,
            #firstName: firstName,
            #lastName: lastName,
            #companyName: companyName,
            #phone: phone,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Seller>>.value(
            _FakeEither_0<_i5.Failure, _i6.Seller>(
          this,
          Invocation.method(
            #registerSeller,
            [],
            {
              #email: email,
              #password: password,
              #firstName: firstName,
              #lastName: lastName,
              #companyName: companyName,
              #phone: phone,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Seller>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Seller>> loginSeller({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginSeller,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Seller>>.value(
            _FakeEither_0<_i5.Failure, _i6.Seller>(
          this,
          Invocation.method(
            #loginSeller,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Seller>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> logoutSeller() =>
      (super.noSuchMethod(
        Invocation.method(
          #logoutSeller,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #logoutSeller,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> sendPasswordResetEmail(
          String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [email],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #sendPasswordResetEmail,
            [email],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updatePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [],
          {
            #currentPassword: currentPassword,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updatePassword,
            [],
            {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Seller>> getCurrentSeller() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentSeller,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Seller>>.value(
            _FakeEither_0<_i5.Failure, _i6.Seller>(
          this,
          Invocation.method(
            #getCurrentSeller,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Seller>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Seller>> updateSellerProfile(
          _i6.Seller? seller) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSellerProfile,
          [seller],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Seller>>.value(
            _FakeEither_0<_i5.Failure, _i6.Seller>(
          this,
          Invocation.method(
            #updateSellerProfile,
            [seller],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Seller>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> sendEmailVerification() =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #sendEmailVerification,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> verifyEmail(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyEmail,
          [token],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #verifyEmail,
            [token],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
