-- Ajout massif de toutes les pièces possibles et imaginables

-- ========================================
-- MOTEUR (pièces ultra détaillées)
-- ========================================
INSERT INTO public.parts (name, category, subcategory, synonyms, is_popular) VALUES
('Axe de piston', 'moteur', 'mecanique', ARRAY['maneton'], false),
('Bague de compression', 'moteur', 'etancheite', ARRAY['segment compression'], false),
('Bague de guidage de soupape', 'moteur', 'distribution', ARRAY['guide soupape'], false),
('Bague racleur d''huile', 'moteur', 'etancheite', ARRAY['segment racleur'], false),
('Boîtier papillon motorisé', 'moteur', 'admission', ARRAY['papillon électrique'], true),
('Boîtier thermostat', 'moteur', 'refroidissement', ARRAY['support thermostat'], false),
('Boulon de bielle', 'moteur', 'fixation', ARRAY['vis de bielle'], false),
('Boulon de culasse', 'moteur', 'fixation', ARRAY['vis culasse'], true),
('Boulon de volant moteur', 'moteur', 'fixation', ARRAY['vis volant'], false),
('Bride de pompe à eau', 'moteur', 'refroidissement', ARRAY['support pompe'], false),
('Cache distribution', 'moteur', 'protection', ARRAY['carter timing'], false),
('Cache soupape', 'moteur', 'protection', ARRAY['couvre soupape'], false),
('Carter de distribution', 'moteur', 'protection', ARRAY['cache timing'], false),
('Carter de protection sous moteur', 'moteur', 'protection', ARRAY['carter sous caisse'], true),
('Chapeau de bielle', 'moteur', 'mecanique', ARRAY['couvercle bielle'], false),
('Chaîne de distribution', 'moteur', 'distribution', ARRAY['chaîne timing'], true),
('Chemise de cylindre', 'moteur', 'mecanique', ARRAY['fourreau cylindre'], false),
('Clapet de décharge turbo', 'moteur', 'suralimentation', ARRAY['wastegate'], false),
('Clapet PCV', 'moteur', 'recyclage', ARRAY['valve reniflard'], false),
('Collecteur admission', 'moteur', 'admission', ARRAY['manifold admission'], true),
('Coupelle de ressort de soupape', 'moteur', 'distribution', ARRAY['siège ressort'], false),
('Couvercle de distribution', 'moteur', 'protection', ARRAY['cache courroie'], false),
('Durit de by-pass', 'moteur', 'refroidissement', ARRAY['tuyau dérivation'], false),
('Durite de dépression', 'moteur', 'depression', ARRAY['tuyau vide'], false),
('Durite de reniflard', 'moteur', 'ventilation', ARRAY['tuyau reniflard'], false),
('Durite de retour d''huile turbo', 'moteur', 'turbo', ARRAY['tuyau retour turbo'], false),
('Durite de suralimentation', 'moteur', 'turbo', ARRAY['durite intercooler'], true),
('Échangeur air-air', 'moteur', 'refroidissement', ARRAY['intercooler'], true),
('Électrovanne de turbo', 'moteur', 'suralimentation', ARRAY['N75'], false),
('Électrovanne purge canister', 'moteur', 'antipollution', ARRAY['purge charbon'], false),
('Fixation moteur avant', 'moteur', 'support', ARRAY['silent-bloc moteur AV'], true),
('Fixation moteur arrière', 'moteur', 'support', ARRAY['silent-bloc moteur AR'], true),
('Flasque de vilebrequin', 'moteur', 'mecanique', ARRAY['bride vilo'], false),
('Galet enrouleur', 'moteur', 'distribution', ARRAY['galet courroie'], true),
('Galet tendeur de chaîne', 'moteur', 'distribution', ARRAY['tendeur chaîne'], false),
('Guide de chaîne', 'moteur', 'distribution', ARRAY['rail chaîne'], false),
('Guide de courroie', 'moteur', 'distribution', ARRAY['rail courroie'], false),
('Joint de carter de distribution', 'moteur', 'etancheite', ARRAY['joint timing'], false),
('Joint de collecteur admission', 'moteur', 'etancheite', ARRAY['joint manifold'], false),
('Joint de couvre-soupapes', 'moteur', 'etancheite', ARRAY['joint cache culasse'], false),
('Joint de culasse renforcé', 'moteur', 'etancheite', ARRAY['joint culasse préparé'], false),
('Joint de pipe admission', 'moteur', 'etancheite', ARRAY['joint tubulure'], false),
('Joint de pompe à vide', 'moteur', 'etancheite', ARRAY['joint pompe vide'], false),
('Joint de refroidisseur d''huile', 'moteur', 'etancheite', ARRAY['joint radiateur huile'], false),
('Joint de turbocompresseur', 'moteur', 'etancheite', ARRAY['joint turbo'], true),
('Joint torique de pompe à eau', 'moteur', 'etancheite', ARRAY['O-ring pompe'], false),
('Kit bielle renforcée', 'moteur', 'performance', ARRAY['bielles forgées'], false),
('Kit joint moteur complet', 'moteur', 'etancheite', ARRAY['pochette joints'], true),
('Kit piston surdimensionné', 'moteur', 'reparation', ARRAY['pistons cote réparation'], false),
('Membrane wastegate', 'moteur', 'turbo', ARRAY['capsule wastegate'], false),
('Noix de culbuteur', 'moteur', 'distribution', ARRAY['pastille culbuteur'], false),
('Pignon d''arbre à cames', 'moteur', 'distribution', ARRAY['poulie AAC'], false),
('Pignon de pompe à huile', 'moteur', 'lubrification', ARRAY['engrenage pompe'], false),
('Pignon de vilebrequin', 'moteur', 'distribution', ARRAY['poulie vilo timing'], false),
('Piston', 'moteur', 'mecanique', ARRAY['piston moteur'], true),
('Plaque anti-retour huile', 'moteur', 'lubrification', ARRAY['clapet huile'], false),
('Plot moteur gauche', 'moteur', 'support', ARRAY['support moteur G'], true),
('Plot moteur droit', 'moteur', 'support', ARRAY['support moteur D'], true),
('Pompe à dépression', 'moteur', 'assistance', ARRAY['pompe vide'], false),
('Pompe à huile haute pression', 'moteur', 'lubrification', ARRAY['pompe HP huile'], false),
('Poussoir hydraulique', 'moteur', 'distribution', ARRAY['poussoir AAC'], false),
('Poulie damper', 'moteur', 'distribution', ARRAY['poulie amortisseur'], false),
('Poulie débrayable', 'moteur', 'distribution', ARRAY['poulie roue libre'], false),
('Refroidisseur d''air de suralimentation', 'moteur', 'turbo', ARRAY['radiateur turbo'], false),
('Refroidisseur d''huile moteur', 'moteur', 'lubrification', ARRAY['radiateur huile'], true),
('Reniflard d''huile', 'moteur', 'ventilation', ARRAY['déshuileur'], false),
('Ressort de soupape', 'moteur', 'distribution', ARRAY['ressort AAC'], false),
('Soupape d''admission', 'moteur', 'distribution', ARRAY['soupape entrée'], false),
('Soupape d''échappement', 'moteur', 'distribution', ARRAY['soupape sortie'], false),
('Support d''alternateur', 'moteur', 'fixation', ARRAY['console alternateur'], false),
('Support de filtre à gasoil', 'moteur', 'fixation', ARRAY['porte filtre diesel'], false),
('Support de pompe à injection', 'moteur', 'fixation', ARRAY['console pompe'], false),
('Tendeur de chaîne distribution', 'moteur', 'distribution', ARRAY['tendeur timing'], false),
('Tuyau de mise à l''air libre', 'moteur', 'ventilation', ARRAY['durite reniflard'], false),
('Valve de décharge', 'moteur', 'turbo', ARRAY['dump valve'], false),
('Vanne d''admission variable', 'moteur', 'admission', ARRAY['swirl'], false),
('Vis de volant moteur', 'moteur', 'fixation', ARRAY['boulon volant'], false),

-- ========================================
-- CARROSSERIE (ultra complet)
-- ========================================
('Agrafe de bas de caisse', 'carrosserie', 'fixation', ARRAY['clip soubassement'], false),
('Agrafe de garniture', 'carrosserie', 'fixation', ARRAY['clip habillage'], false),
('Agrafe de passage de roue', 'carrosserie', 'fixation', ARRAY['clip doublure'], false),
('Aile avant droite', 'carrosserie', 'panneaux', ARRAY['aile AV D'], true),
('Aile avant gauche', 'carrosserie', 'panneaux', ARRAY['aile AV G'], true),
('Aile arrière droite', 'carrosserie', 'panneaux', ARRAY['aile AR D'], true),
('Aile arrière gauche', 'carrosserie', 'panneaux', ARRAY['aile AR G'], true),
('Bas de caisse droit', 'carrosserie', 'protection', ARRAY['soubassement D'], false),
('Bas de caisse gauche', 'carrosserie', 'protection', ARRAY['soubassement G'], false),
('Becquet de coffre', 'carrosserie', 'aero', ARRAY['aileron'], true),
('Becquet de toit', 'carrosserie', 'aero', ARRAY['spoiler'], false),
('Bouchon de rétroviseur', 'carrosserie', 'protection', ARRAY['cache rétro'], false),
('Cache boulon de roue', 'carrosserie', 'esthetique', ARRAY['cache écrou'], false),
('Cache prise d''air', 'carrosserie', 'esthetique', ARRAY['trappe prise'], false),
('Calandre centrale', 'carrosserie', 'facade', ARRAY['grille centrale'], true),
('Capot avant', 'carrosserie', 'panneaux', ARRAY['bonnet'], true),
('Capot moteur', 'carrosserie', 'panneaux', ARRAY['capot AV'], true),
('Coque de rétroviseur droit', 'carrosserie', 'habillage', ARRAY['cache rétro D'], true),
('Coque de rétroviseur gauche', 'carrosserie', 'habillage', ARRAY['cache rétro G'], true),
('Entourage antibrouillard droit', 'carrosserie', 'garniture', ARRAY['cache antibrouillard D'], false),
('Entourage antibrouillard gauche', 'carrosserie', 'garniture', ARRAY['cache antibrouillard G'], false),
('Fermeture de hayon', 'carrosserie', 'serrurerie', ARRAY['serrure coffre'], true),
('Glace de rétroviseur droit', 'carrosserie', 'optique', ARRAY['miroir rétro D'], true),
('Glace de rétroviseur gauche', 'carrosserie', 'optique', ARRAY['miroir rétro G'], true),
('Grille aération capot', 'carrosserie', 'ventilation', ARRAY['prise d''air capot'], false),
('Grille de calandre', 'carrosserie', 'facade', ARRAY['grille radiateur'], true),
('Jonc de porte', 'carrosserie', 'protection', ARRAY['baguette porte'], false),
('Jonc d''aile', 'carrosserie', 'protection', ARRAY['baguette aile'], false),
('Malle arrière', 'carrosserie', 'panneaux', ARRAY['coffre'], false),
('Moulure de porte avant droite', 'carrosserie', 'decoration', ARRAY['baguette porte AV D'], false),
('Moulure de porte avant gauche', 'carrosserie', 'decoration', ARRAY['baguette porte AV G'], false),
('Panneau arrière', 'carrosserie', 'structure', ARRAY['tablier AR'], false),
('Panneau avant', 'carrosserie', 'structure', ARRAY['tablier AV'], false),
('Pare-boue avant droit', 'carrosserie', 'protection', ARRAY['bavette AV D'], false),
('Pare-boue avant gauche', 'carrosserie', 'protection', ARRAY['bavette AV G'], false),
('Pare-boue arrière droit', 'carrosserie', 'protection', ARRAY['bavette AR D'], false),
('Pare-boue arrière gauche', 'carrosserie', 'protection', ARRAY['bavette AR G'], false),
('Pare-chocs avant', 'carrosserie', 'protection', ARRAY['pare-chocs AV'], true),
('Pare-chocs arrière', 'carrosserie', 'protection', ARRAY['pare-chocs AR'], true),
('Pied de pare-chocs avant droit', 'carrosserie', 'fixation', ARRAY['support pare-chocs AV D'], false),
('Pied de pare-chocs avant gauche', 'carrosserie', 'fixation', ARRAY['support pare-chocs AV G'], false),
('Porte avant droite', 'carrosserie', 'panneaux', ARRAY['porte AV D'], true),
('Porte avant gauche', 'carrosserie', 'panneaux', ARRAY['porte AV G'], true),
('Porte arrière droite', 'carrosserie', 'panneaux', ARRAY['porte AR D'], true),
('Porte arrière gauche', 'carrosserie', 'panneaux', ARRAY['porte AR G'], true),
('Poignée de porte avant droite', 'carrosserie', 'accessoire', ARRAY['poignée AV D'], true),
('Poignée de porte avant gauche', 'carrosserie', 'accessoire', ARRAY['poignée AV G'], true),
('Poignée de porte arrière droite', 'carrosserie', 'accessoire', ARRAY['poignée AR D'], false),
('Poignée de porte arrière gauche', 'carrosserie', 'accessoire', ARRAY['poignée AR G'], false),
('Prise d''air de capot', 'carrosserie', 'ventilation', ARRAY['écope capot'], false),
('Protection de seuil avant droit', 'carrosserie', 'protection', ARRAY['baguette seuil AV D'], false),
('Protection de seuil avant gauche', 'carrosserie', 'protection', ARRAY['baguette seuil AV G'], false),
('Rabat de phare', 'carrosserie', 'optique', ARRAY['volet phare escamotable'], false),
('Rétroviseur extérieur droit', 'carrosserie', 'vision', ARRAY['rétro D'], true),
('Rétroviseur extérieur gauche', 'carrosserie', 'vision', ARRAY['rétro G'], true),
('Serrure de porte avant droite', 'carrosserie', 'serrurerie', ARRAY['gâche AV D'], true),
('Serrure de porte avant gauche', 'carrosserie', 'serrurerie', ARRAY['gâche AV G'], true),
('Soubassement', 'carrosserie', 'structure', ARRAY['plancher'], false),
('Support de plaque avant', 'carrosserie', 'fixation', ARRAY['porte-plaque AV'], false),
('Support de plaque arrière', 'carrosserie', 'fixation', ARRAY['porte-plaque AR'], false),
('Trappe à essence', 'carrosserie', 'acces', ARRAY['volet réservoir'], true),
('Traverse de châssis', 'carrosserie', 'structure', ARRAY['longeron'], false),
('Vérin de capot', 'carrosserie', 'assistance', ARRAY['amortisseur capot'], false),
('Vérin de coffre', 'carrosserie', 'assistance', ARRAY['amortisseur coffre'], true),

-- ========================================
-- TRANSMISSION (détaillée)
-- ========================================
('Arbre de transmission', 'transmission', 'transmission', ARRAY['arbre prop'], false),
('Cardan côté boîte droit', 'transmission', 'transmission', ARRAY['cardan D boîte'], true),
('Cardan côté boîte gauche', 'transmission', 'transmission', ARRAY['cardan G boîte'], true),
('Cardan côté roue droit', 'transmission', 'transmission', ARRAY['cardan D roue'], true),
('Cardan côté roue gauche', 'transmission', 'transmission', ARRAY['cardan G roue'], true),
('Câble de boîte de vitesses', 'transmission', 'commande', ARRAY['câble sélecteur'], false),
('Câble d''embrayage', 'transmission', 'commande', ARRAY['câble pédale'], true),
('Croisillon de cardan', 'transmission', 'liaison', ARRAY['joint cardan'], false),
('Différentiel arrière', 'transmission', 'transmission', ARRAY['pont AR'], false),
('Disque d''embrayage', 'transmission', 'embrayage', ARRAY['friction'], true),
('Engrenage de boîte', 'transmission', 'boite', ARRAY['pignon vitesse'], false),
('Filtre de boîte automatique', 'transmission', 'entretien', ARRAY['filtre BVA'], true),
('Huile de boîte de vitesses', 'transmission', 'fluide', ARRAY['huile BV'], true),
('Huile de pont', 'transmission', 'fluide', ARRAY['huile différentiel'], false),
('Joint homocinétique', 'transmission', 'liaison', ARRAY['joint tulipe'], true),
('Joint de cardan', 'transmission', 'etancheite', ARRAY['soufflet transmission'], true),
('Kit d''embrayage complet', 'transmission', 'embrayage', ARRAY['kit embrayage'], true),
('Levier de vitesses', 'transmission', 'commande', ARRAY['pommeau vitesses'], true),
('Palier de transmission', 'transmission', 'support', ARRAY['roulement arbre'], false),
('Pièce d''usure embrayage', 'transmission', 'embrayage', ARRAY['garniture embrayage'], false),
('Récepteur d''embrayage', 'transmission', 'hydraulique', ARRAY['cylindre récepteur'], true),
('Support d''arbre de transmission', 'transmission', 'fixation', ARRAY['palier prop'], false),
('Timonerie de boîte', 'transmission', 'commande', ARRAY['tringlerie BV'], false),
('Trompette de cardan', 'transmission', 'transmission', ARRAY['tulipe'], false),

-- ========================================
-- FREINAGE (ultra détaillé)
-- ========================================
('Disque de frein avant droit', 'freinage', 'mecanique', ARRAY['disque AV D'], true),
('Disque de frein avant gauche', 'freinage', 'mecanique', ARRAY['disque AV G'], true),
('Disque de frein arrière droit', 'freinage', 'mecanique', ARRAY['disque AR D'], true),
('Disque de frein arrière gauche', 'freinage', 'mecanique', ARRAY['disque AR G'], true),
('Disque de frein ventilé', 'freinage', 'mecanique', ARRAY['disque aéré'], true),
('Disque de frein percé', 'freinage', 'performance', ARRAY['disque sport'], false),
('Durite de frein avant droit', 'freinage', 'hydraulique', ARRAY['flexible frein AV D'], false),
('Durite de frein avant gauche', 'freinage', 'hydraulique', ARRAY['flexible frein AV G'], false),
('Durite de frein arrière droit', 'freinage', 'hydraulique', ARRAY['flexible frein AR D'], false),
('Durite de frein arrière gauche', 'freinage', 'hydraulique', ARRAY['flexible frein AR G'], false),
('Durite aviation', 'freinage', 'performance', ARRAY['durite tressée'], false),
('Joint de maître-cylindre', 'freinage', 'etancheite', ARRAY['joint MC'], false),
('Kit de réparation étrier', 'freinage', 'reparation', ARRAY['kit joint étrier'], false),
('Maître-cylindre de frein', 'freinage', 'hydraulique', ARRAY['cylindre maître'], true),
('Membrane de servo-frein', 'freinage', 'assistance', ARRAY['diaphragme servo'], false),
('Plaquettes céramique', 'freinage', 'performance', ARRAY['plaquettes racing'], false),
('Piston d''étrier', 'freinage', 'mecanique', ARRAY['piston frein'], false),
('Tambour de frein avant', 'freinage', 'mecanique', ARRAY['tambour AV'], false),
('Tambour de frein arrière', 'freinage', 'mecanique', ARRAY['tambour AR'], true),

-- ========================================
-- SUSPENSION (encore plus détaillé)
-- ========================================
('Amortisseur avant droit', 'suspension', 'amortissement', ARRAY['amortisseur AV D'], true),
('Amortisseur avant gauche', 'suspension', 'amortissement', ARRAY['amortisseur AV G'], true),
('Amortisseur arrière droit', 'suspension', 'amortissement', ARRAY['amortisseur AR D'], true),
('Amortisseur arrière gauche', 'suspension', 'amortissement', ARRAY['amortisseur AR G'], true),
('Amortisseur à gaz', 'suspension', 'amortissement', ARRAY['amortisseur gazeux'], true),
('Bague de bras oscillant', 'suspension', 'liaison', ARRAY['silent-bloc oscillant'], false),
('Barre de torsion', 'suspension', 'mecanique', ARRAY['ressort torsion'], false),
('Berceau de train avant', 'suspension', 'structure', ARRAY['sous-châssis AV'], false),
('Berceau de train arrière', 'suspension', 'structure', ARRAY['sous-châssis AR'], false),
('Bras tiré', 'suspension', 'liaison', ARRAY['bras longitudinal'], false),
('Châssis de suspension', 'suspension', 'structure', ARRAY['berceau'], false),
('Combiné fileté', 'suspension', 'performance', ARRAY['coilover'], false),
('Correcteur de hauteur', 'suspension', 'regulation', ARRAY['correcteur assiette'], false),
('Coussin pneumatique', 'suspension', 'confort', ARRAY['suspension air'], false),
('Jambe de force avant droite', 'suspension', 'amortissement', ARRAY['jambe AV D'], true),
('Jambe de force avant gauche', 'suspension', 'amortissement', ARRAY['jambe AV G'], true),
('Kit silent-bloc complet', 'suspension', 'liaison', ARRAY['kit caoutchoucs'], false),
('Rotule de direction droite', 'suspension', 'liaison', ARRAY['rotule D'], true),
('Rotule de direction gauche', 'suspension', 'liaison', ARRAY['rotule G'], true),
('Soufflet d''amortisseur avant', 'suspension', 'protection', ARRAY['soufflet jambe AV'], false),
('Soufflet d''amortisseur arrière', 'suspension', 'protection', ARRAY['soufflet jambe AR'], false),
('Sphère de suspension', 'suspension', 'hydraulique', ARRAY['sphère hydro'], false),
('Support d''amortisseur', 'suspension', 'fixation', ARRAY['coupelle amortisseur'], true),
('Tirant de suspension', 'suspension', 'liaison', ARRAY['bielle suspension'], false),
('Triangle de suspension droit', 'suspension', 'mecanique', ARRAY['bras D'], true),
('Triangle de suspension gauche', 'suspension', 'mecanique', ARRAY['bras G'], true),

-- ========================================
-- DIRECTION (complet)
-- ========================================
('Boîtier de direction', 'direction', 'mecanique', ARRAY['carter direction'], false),
('Bras de direction', 'direction', 'liaison', ARRAY['bras pitman'], false),
('Colonne direction réglable', 'direction', 'confort', ARRAY['colonne ajustable'], false),
('Joint de direction', 'direction', 'liaison', ARRAY['cardan direction'], false),
('Manchon de direction', 'direction', 'protection', ARRAY['soufflet colonne'], false),
('Rotule axiale droite', 'direction', 'liaison', ARRAY['rotule axiale D'], true),
('Rotule axiale gauche', 'direction', 'liaison', ARRAY['rotule axiale G'], true),
('Timonerie complète', 'direction', 'mecanique', ARRAY['tringlerie complète'], false),
('Vérin de direction', 'direction', 'assistance', ARRAY['vérin DA'], false),

-- ========================================
-- CLIMATISATION (très détaillé)
-- ========================================
('Buse de ventilation centrale', 'climatisation', 'diffusion', ARRAY['aérateur central'], false),
('Buse de ventilation latérale', 'climatisation', 'diffusion', ARRAY['aérateur latéral'], false),
('Câble de commande de chauffage', 'climatisation', 'commande', ARRAY['câble température'], false),
('Carter de ventilation', 'climatisation', 'boitier', ARRAY['boîtier ventilation'], false),
('Clapet de recyclage d''air', 'climatisation', 'regulation', ARRAY['volet recyclage'], false),
('Condensateur auxiliaire', 'climatisation', 'echange', ARRAY['condenseur additionnel'], false),
('Filtre antibactérien', 'climatisation', 'filtration', ARRAY['filtre habitacle antibac'], false),
('Filtre au charbon actif', 'climatisation', 'filtration', ARRAY['filtre charbon'], true),
('Groupe de ventilation', 'climatisation', 'ventilation', ARRAY['caisson ventilation'], false),
('Pulseur d''air avant', 'climatisation', 'ventilation', ARRAY['ventilateur AV'], true),
('Pulseur d''air arrière', 'climatisation', 'ventilation', ARRAY['ventilateur AR'], false),
('Radiateur de chauffage', 'climatisation', 'chauffage', ARRAY['radiateur habitacle'], true),
('Régulateur de vitesse ventilation', 'climatisation', 'regulation', ARRAY['résistance pulseur'], true),
('Robinet de chauffage', 'climatisation', 'regulation', ARRAY['vanne chauffage'], false),
('Sonde d''ensoleillement', 'climatisation', 'regulation', ARRAY['capteur soleil'], false),
('Tuyau de drainage clim', 'climatisation', 'evacuation', ARRAY['durite évacuation'], false),
('Vanne de régulation clim', 'climatisation', 'regulation', ARRAY['valve expansion'], false),
('Volet de mixage', 'climatisation', 'regulation', ARRAY['clapet température'], false),

-- ========================================
-- ÉLECTRONIQUE (très avancé)
-- ========================================
('Actionneur de coffre électrique', 'electronique', 'confort', ARRAY['moteur coffre'], false),
('Actionneur de trappe essence', 'electronique', 'confort', ARRAY['moteur trappe'], false),
('Antenne amplifiée', 'electronique', 'multimedia', ARRAY['antenne active'], false),
('Boîtier d''aide au stationnement', 'electronique', 'aide', ARRAY['radar recul'], true),
('Boîtier électronique d''airbag', 'electronique', 'securite', ARRAY['ECU airbag'], true),
('Boîtier fusibles habitacle', 'electronique', 'distribution', ARRAY['boîte fusibles intérieur'], true),
('Boîtier fusibles moteur', 'electronique', 'distribution', ARRAY['boîte fusibles compartiment moteur'], true),
('Calculateur ABS', 'electronique', 'freinage', ARRAY['ECU ABS'], true),
('Calculateur boîte automatique', 'electronique', 'transmission', ARRAY['ECU BVA'], false),
('Calculateur carburant', 'electronique', 'gestion', ARRAY['ECU injection'], true),
('Calculateur de climatisation', 'electronique', 'climatisation', ARRAY['ECU clim'], false),
('Calculateur ESP', 'electronique', 'securite', ARRAY['ECU ESP'], true),
('Caméra 360°', 'electronique', 'vision', ARRAY['caméra panoramique'], false),
('Caméra de stationnement', 'electronique', 'aide', ARRAY['caméra parking'], true),
('Capteur angle volant', 'electronique', 'direction', ARRAY['capteur rotation'], false),
('Capteur de pluie', 'electronique', 'confort', ARRAY['capteur essuie-glace auto'], true),
('Capteur pédale d''embrayage', 'electronique', 'transmission', ARRAY['contacteur embrayage'], false),
('Contacteur de feu stop', 'electronique', 'freinage', ARRAY['contacteur pédale frein'], true),
('Contacteur de pédale de frein', 'electronique', 'freinage', ARRAY['switch frein'], true),
('Contacteur de porte', 'electronique', 'securite', ARRAY['switch porte'], false),
('Écran multimédia', 'electronique', 'multimedia', ARRAY['écran tactile'], true),
('Haut-parleur avant droit', 'electronique', 'audio', ARRAY['HP AV D'], false),
('Haut-parleur avant gauche', 'electronique', 'audio', ARRAY['HP AV G'], false),
('Haut-parleur arrière droit', 'electronique', 'audio', ARRAY['HP AR D'], false),
('Haut-parleur arrière gauche', 'electronique', 'audio', ARRAY['HP AR G'], false),
('Module d''amplification audio', 'electronique', 'audio', ARRAY['ampli son'], false),
('Module keyless', 'electronique', 'confort', ARRAY['démarrage sans clé'], true),
('Module régulateur de vitesse', 'electronique', 'aide', ARRAY['cruise control'], true),
('Platine de commande au volant', 'electronique', 'commande', ARRAY['commandes volant'], false),
('Radar d''angle mort', 'electronique', 'securite', ARRAY['capteur angle mort'], true),
('Radar de stationnement avant', 'electronique', 'aide', ARRAY['capteur parking AV'], true),
('Radar de stationnement arrière', 'electronique', 'aide', ARRAY['capteur parking AR'], true),
('Système audio', 'electronique', 'multimedia', ARRAY['autoradio'], true),
('Système de démarrage à distance', 'electronique', 'confort', ARRAY['télécommande démarrage'], false),
('Télécommande de centralisation', 'electronique', 'confort', ARRAY['clé télécommande'], true),
('Unité de commande habitacle', 'electronique', 'confort', ARRAY['BSI'], false),

-- ========================================
-- ÉCHAPPEMENT (très complet)
-- ========================================
('Collier d''échappement', 'echappement', 'fixation', ARRAY['collier tuyau'], false),
('Manchon d''échappement', 'echappement', 'reparation', ARRAY['manchon réparation'], false),
('Tube de descente turbo', 'echappement', 'evacuation', ARRAY['downpipe'], false),
('Tube intermédiaire inox', 'echappement', 'evacuation', ARRAY['pipe centrale inox'], false),

-- ========================================
-- ACCESSOIRES (complet)
-- ========================================
('Boule d''attelage', 'accessoires', 'remorquage', ARRAY['rotule attelage'], true),
('Câble de remorquage', 'accessoires', 'securite', ARRAY['sangle remorquage'], false),
('Câble OBD Bluetooth', 'accessoires', 'diagnostic', ARRAY['adaptateur OBD'], false),
('Cache roue de secours', 'accessoires', 'protection', ARRAY['housse galette'], false),
('Clé de roue', 'accessoires', 'outillage', ARRAY['croix démonte-pneu'], true),
('Clé dynamométrique', 'accessoires', 'outillage', ARRAY['clé couple'], false),
('Compresseur portable', 'accessoires', 'entretien', ARRAY['gonfleur'], false),
('Cric hydraulique', 'accessoires', 'outillage', ARRAY['vérin hydraulique'], false),
('Gilet de sécurité', 'accessoires', 'securite', ARRAY['gilet jaune'], true),
('Kit anti-crevaison', 'accessoires', 'reparation', ARRAY['bombe anti-crevaison'], false),
('Lampe torche', 'accessoires', 'securite', ARRAY['lampe urgence'], false),
('Manomètre de pression', 'accessoires', 'controle', ARRAY['jauge pression pneus'], false),
('Pare-soleil avant', 'accessoires', 'confort', ARRAY['pare-brise solaire'], false),
('Pompe à carburant manuelle', 'accessoires', 'entretien', ARRAY['pompe transfert'], false),
('Support téléphone', 'accessoires', 'multimedia', ARRAY['fixation smartphone'], false),
('Tapis caoutchouc', 'accessoires', 'protection', ARRAY['tapis tout-temps'], true)

ON CONFLICT (name) DO NOTHING;
