-- Ajout ultra complet final avec toutes les pièces détaillées restantes

-- ========================================
-- CARBURANT (détails finaux manquants)
-- ========================================
INSERT INTO public.parts (name, category, subcategory, synonyms, is_popular) VALUES
('Pompe de gavage', 'carburant', 'alimentation', ARRAY['pompe basse pression'], false),
('Tuyaux carburant aller', 'carburant', 'alimentation', ARRAY['canalisation aller'], false),
('Tuyaux carburant retour', 'carburant', 'alimentation', ARRAY['canalisation retour'], false),
('Capteur de température carburant', 'carburant', 'mesure', ARRAY['sonde température carburant'], false),
('Conduites retour carburant', 'carburant', 'alimentation', ARRAY['tuyaux retour'], false),

-- ========================================
-- REFROIDISSEMENT (ultra complet)
-- ========================================
('Radiateur moteur', 'moteur', 'refroidissement', ARRAY['échangeur eau'], true),
('Ventilateur de radiateur', 'moteur', 'refroidissement', ARRAY['électro-ventilateur'], true),
('Moteur de ventilateur', 'moteur', 'refroidissement', ARRAY['moteur électro-ventilateur'], true),
('Carter de ventilateur', 'moteur', 'refroidissement', ARRAY['carénage ventilateur'], false),
('Pompe à eau', 'moteur', 'refroidissement', ARRAY['water pump'], true),
('Poulie pompe à eau', 'moteur', 'refroidissement', ARRAY['poulie water pump'], false),
('Thermostat boîtier', 'moteur', 'refroidissement', ARRAY['calorstat complet'], true),
('Durite supérieure radiateur', 'moteur', 'refroidissement', ARRAY['durite haute radiateur'], true),
('Durite inférieure radiateur', 'moteur', 'refroidissement', ARRAY['durite basse radiateur'], true),
('Vase d''expansion', 'moteur', 'refroidissement', ARRAY['bocal liquide refroidissement'], true),
('Bouchon de vase', 'moteur', 'refroidissement', ARRAY['bouchon expansion'], false),
('Capteur de température liquide', 'moteur', 'mesure', ARRAY['sonde température eau'], true),
('Capteur de niveau liquide', 'moteur', 'mesure', ARRAY['sonde niveau liquide refroidissement'], false),
('Radiateur chauffage habitacle', 'climatisation', 'chauffage', ARRAY['radiateur chauffage'], true),
('Tuyau de chauffage aller', 'climatisation', 'chauffage', ARRAY['durite chauffage entrée'], false),
('Tuyau de chauffage retour', 'climatisation', 'chauffage', ARRAY['durite chauffage sortie'], false),
('Ventilateur chauffage', 'climatisation', 'chauffage', ARRAY['pulseur habitacle'], true),
('Vanne de chauffage', 'climatisation', 'regulation', ARRAY['robinet chauffage'], false),
('Résistance de ventilateur chauffage', 'climatisation', 'regulation', ARRAY['résistance pulseur'], true),

-- ========================================
-- LUBRIFICATION (complet)
-- ========================================
('Pompe à huile', 'moteur', 'lubrification', ARRAY['pompe graissage'], true),
('Carter d''huile', 'moteur', 'lubrification', ARRAY['carter huile moteur'], true),
('Jauge à huile', 'moteur', 'mesure', ARRAY['tige niveau huile'], true),
('Bouchon de remplissage huile', 'moteur', 'entretien', ARRAY['bouchon huile moteur'], true),
('Filtre à huile', 'moteur', 'filtration', ARRAY['cartouche huile'], true),
('Refroidisseur d''huile', 'moteur', 'lubrification', ARRAY['radiateur huile'], true),
('Capteur de pression d''huile', 'moteur', 'mesure', ARRAY['manocontact huile'], true),
('Canalisation huile turbo aller', 'moteur', 'turbo', ARRAY['tuyau graissage turbo'], false),
('Canalisation huile turbo retour', 'moteur', 'turbo', ARRAY['tuyau retour turbo'], false),
('Joint carter huile', 'moteur', 'etancheite', ARRAY['joint carter inférieur'], true),
('Tuyau de retour huile', 'moteur', 'lubrification', ARRAY['durite retour huile'], false),
('Crépine pompe à huile', 'moteur', 'lubrification', ARRAY['tamis pompe huile'], false),
('Tube de jauge huile', 'moteur', 'mesure', ARRAY['guide jauge'], false),

-- ========================================
-- TRANSMISSION (ultra détaillée)
-- ========================================
('Boîte de vitesses manuelle', 'transmission', 'boite', ARRAY['BVM'], true),
('Boîte automatique', 'transmission', 'boite', ARRAY['BVA'], true),
('Boîte robotisée', 'transmission', 'boite', ARRAY['BVR'], false),
('Convertisseur de couple', 'transmission', 'boite', ARRAY['convertisseur BVA'], true),
('Embrayage complet', 'transmission', 'embrayage', ARRAY['kit embrayage complet'], true),
('Disque d''embrayage', 'transmission', 'embrayage', ARRAY['disque friction'], true),
('Mécanisme d''embrayage', 'transmission', 'embrayage', ARRAY['plateau embrayage'], true),
('Butée d''embrayage', 'transmission', 'embrayage', ARRAY['butée mécanique'], true),
('Butée hydraulique', 'transmission', 'embrayage', ARRAY['butée CSC'], true),
('Récepteur d''embrayage', 'transmission', 'hydraulique', ARRAY['cylindre récepteur embrayage'], true),
('Émetteur d''embrayage', 'transmission', 'hydraulique', ARRAY['maître-cylindre embrayage'], true),
('Fourchette d''embrayage', 'transmission', 'embrayage', ARRAY['fourchette débrayage'], false),
('Câble d''embrayage', 'transmission', 'commande', ARRAY['câble pédale embrayage'], true),
('Cardan gauche', 'transmission', 'transmission', ARRAY['cardan côté G'], true),
('Cardan droit', 'transmission', 'transmission', ARRAY['cardan côté D'], true),
('Soufflet de cardan intérieur', 'transmission', 'protection', ARRAY['soufflet côté boîte'], true),
('Soufflet de cardan extérieur', 'transmission', 'protection', ARRAY['soufflet côté roue'], true),
('Joint homocinétique intérieur', 'transmission', 'liaison', ARRAY['joint tulipe'], true),
('Joint homocinétique extérieur', 'transmission', 'liaison', ARRAY['joint tripode'], true),
('Roulement de cardan', 'transmission', 'mecanique', ARRAY['palier cardan'], false),
('Arbre de transmission', 'transmission', 'transmission', ARRAY['arbre prop'], false),
('Palier central arbre', 'transmission', 'support', ARRAY['support arbre'], false),
('Différentiel', 'transmission', 'transmission', ARRAY['pont'], false),
('Joint spi sortie boîte gauche', 'transmission', 'etancheite', ARRAY['joint spi BV G'], true),
('Joint spi sortie boîte droit', 'transmission', 'etancheite', ARRAY['joint spi BV D'], true),
('Support de boîte de vitesses', 'transmission', 'fixation', ARRAY['silent-bloc BV'], true),
('Levier de vitesses', 'transmission', 'commande', ARRAY['levier sélecteur'], true),
('Tringlerie de vitesses', 'transmission', 'commande', ARRAY['timonerie BV'], false),
('Câble de commande boîte', 'transmission', 'commande', ARRAY['câble sélection'], false),
('Huile de boîte manuelle', 'transmission', 'fluide', ARRAY['huile BVM'], true),
('Huile de boîte automatique', 'transmission', 'fluide', ARRAY['ATF'], true),
('Filtre boîte automatique', 'transmission', 'entretien', ARRAY['filtre BVA'], true),
('Carter de boîte', 'transmission', 'structure', ARRAY['boîtier BV'], false),
('Joint de carter boîte', 'transmission', 'etancheite', ARRAY['joint carter BV'], false),
('Embout de cardan', 'transmission', 'transmission', ARRAY['noix cardan'], false),

-- ========================================
-- SUSPENSION AVANT (ultra détaillée)
-- ========================================
('Amortisseur avant gauche', 'suspension', 'amortissement', ARRAY['amortisseur AV G'], true),
('Amortisseur avant droit', 'suspension', 'amortissement', ARRAY['amortisseur AV D'], true),
('Ressort hélicoïdal avant gauche', 'suspension', 'amortissement', ARRAY['ressort AV G'], true),
('Ressort hélicoïdal avant droit', 'suspension', 'amortissement', ARRAY['ressort AV D'], true),
('Coupelle d''amortisseur avant gauche', 'suspension', 'fixation', ARRAY['coupelle AV G'], true),
('Coupelle d''amortisseur avant droite', 'suspension', 'fixation', ARRAY['coupelle AV D'], true),
('Roulement de tête d''amortisseur avant', 'suspension', 'mecanique', ARRAY['roulement coupelle AV'], false),
('Bras de suspension inférieur gauche', 'suspension', 'liaison', ARRAY['triangle inférieur G'], true),
('Bras de suspension inférieur droit', 'suspension', 'liaison', ARRAY['triangle inférieur D'], true),
('Bras de suspension supérieur gauche', 'suspension', 'liaison', ARRAY['triangle supérieur G'], false),
('Bras de suspension supérieur droit', 'suspension', 'liaison', ARRAY['triangle supérieur D'], false),
('Rotule inférieure gauche', 'suspension', 'liaison', ARRAY['rotule basse G'], true),
('Rotule inférieure droite', 'suspension', 'liaison', ARRAY['rotule basse D'], true),
('Rotule supérieure gauche', 'suspension', 'liaison', ARRAY['rotule haute G'], false),
('Rotule supérieure droite', 'suspension', 'liaison', ARRAY['rotule haute D'], false),
('Biellette de barre stabilisatrice avant gauche', 'suspension', 'liaison', ARRAY['biellette AV G'], true),
('Biellette de barre stabilisatrice avant droite', 'suspension', 'liaison', ARRAY['biellette AV D'], true),
('Barre stabilisatrice avant', 'suspension', 'mecanique', ARRAY['barre anti-roulis AV'], true),
('Silentbloc barre stabilisatrice avant gauche', 'suspension', 'liaison', ARRAY['silentbloc stab AV G'], false),
('Silentbloc barre stabilisatrice avant droite', 'suspension', 'liaison', ARRAY['silentbloc stab AV D'], false),
('Support amortisseur avant', 'suspension', 'fixation', ARRAY['fixation amortisseur AV'], false),
('Berceau avant', 'suspension', 'structure', ARRAY['sous-châssis AV'], false),
('Silentbloc berceau avant', 'suspension', 'liaison', ARRAY['silent-bloc sous-châssis AV'], false),
('Vis de bras avant', 'suspension', 'fixation', ARRAY['boulons triangle AV'], false),
('Fixation berceau avant', 'suspension', 'fixation', ARRAY['visserie berceau AV'], false),

-- ========================================
-- SUSPENSION ARRIÈRE (ultra détaillée)
-- ========================================
('Amortisseur arrière gauche', 'suspension', 'amortissement', ARRAY['amortisseur AR G'], true),
('Amortisseur arrière droit', 'suspension', 'amortissement', ARRAY['amortisseur AR D'], true),
('Ressort hélicoïdal arrière gauche', 'suspension', 'amortissement', ARRAY['ressort AR G'], true),
('Ressort hélicoïdal arrière droit', 'suspension', 'amortissement', ARRAY['ressort AR D'], true),
('Coupelle d''amortisseur arrière gauche', 'suspension', 'fixation', ARRAY['coupelle AR G'], false),
('Coupelle d''amortisseur arrière droite', 'suspension', 'fixation', ARRAY['coupelle AR D'], false),
('Roulement de tête d''amortisseur arrière', 'suspension', 'mecanique', ARRAY['roulement coupelle AR'], false),
('Bras de suspension arrière gauche', 'suspension', 'liaison', ARRAY['triangle arrière G'], true),
('Bras de suspension arrière droit', 'suspension', 'liaison', ARRAY['triangle arrière D'], true),
('Bras longitudinal arrière gauche', 'suspension', 'liaison', ARRAY['bras tiré AR G'], false),
('Bras longitudinal arrière droit', 'suspension', 'liaison', ARRAY['bras tiré AR D'], false),
('Biellette de barre stabilisatrice arrière gauche', 'suspension', 'liaison', ARRAY['biellette AR G'], false),
('Biellette de barre stabilisatrice arrière droite', 'suspension', 'liaison', ARRAY['biellette AR D'], false),
('Barre stabilisatrice arrière', 'suspension', 'mecanique', ARRAY['barre anti-roulis AR'], true),
('Silentbloc barre stabilisatrice arrière', 'suspension', 'liaison', ARRAY['silentbloc stab AR'], false),
('Berceau arrière', 'suspension', 'structure', ARRAY['sous-châssis AR'], false),
('Silentbloc berceau arrière', 'suspension', 'liaison', ARRAY['silent-bloc sous-châssis AR'], false),
('Support amortisseur arrière', 'suspension', 'fixation', ARRAY['fixation amortisseur AR'], false),

-- ========================================
-- DIRECTION (ultra détaillée)
-- ========================================
('Crémaillère de direction', 'direction', 'mecanique', ARRAY['boîtier direction'], true),
('Crémaillère assistée électrique', 'direction', 'assistance', ARRAY['DAE'], true),
('Crémaillère assistée hydraulique', 'direction', 'assistance', ARRAY['DA hydraulique'], true),
('Pompe de direction assistée', 'direction', 'hydraulique', ARRAY['pompe DA'], true),
('Réservoir de direction assistée', 'direction', 'hydraulique', ARRAY['bocal DA'], false),
('Flexible de direction assistée', 'direction', 'hydraulique', ARRAY['durite DA'], false),
('Liquide de direction assistée', 'direction', 'fluide', ARRAY['huile DA'], true),
('Soufflet de crémaillère gauche', 'direction', 'protection', ARRAY['soufflet direction G'], true),
('Soufflet de crémaillère droit', 'direction', 'protection', ARRAY['soufflet direction D'], true),
('Rotule de direction gauche', 'direction', 'liaison', ARRAY['rotule axiale G'], true),
('Rotule de direction droite', 'direction', 'liaison', ARRAY['rotule axiale D'], true),
('Biellette de direction gauche', 'direction', 'liaison', ARRAY['bielle direction G'], true),
('Biellette de direction droite', 'direction', 'liaison', ARRAY['bielle direction D'], true),
('Colonne de direction', 'direction', 'mecanique', ARRAY['arbre direction'], true),
('Cardan de colonne de direction', 'direction', 'liaison', ARRAY['joint cardan direction'], false),
('Support de crémaillère', 'direction', 'fixation', ARRAY['fixation crémaillère'], false),
('Kit fixation crémaillère', 'direction', 'fixation', ARRAY['silent-blocs crémaillère'], false),
('Moteur de direction assistée électrique', 'direction', 'assistance', ARRAY['moteur DAE'], true),
('Capteur de couple direction', 'direction', 'mesure', ARRAY['capteur effort volant'], false),

-- ========================================
-- FREINAGE (ultra détaillé)
-- ========================================
('Disque de frein avant gauche', 'freinage', 'mecanique', ARRAY['disque AV G'], true),
('Disque de frein avant droit', 'freinage', 'mecanique', ARRAY['disque AV D'], true),
('Disque de frein arrière gauche', 'freinage', 'mecanique', ARRAY['disque AR G'], true),
('Disque de frein arrière droit', 'freinage', 'mecanique', ARRAY['disque AR D'], true),
('Plaquettes de frein avant', 'freinage', 'mecanique', ARRAY['plaquettes AV'], true),
('Plaquettes de frein arrière', 'freinage', 'mecanique', ARRAY['plaquettes AR'], true),
('Étrier de frein avant gauche', 'freinage', 'mecanique', ARRAY['étrier AV G'], true),
('Étrier de frein avant droit', 'freinage', 'mecanique', ARRAY['étrier AV D'], true),
('Étrier de frein arrière gauche', 'freinage', 'mecanique', ARRAY['étrier AR G'], true),
('Étrier de frein arrière droit', 'freinage', 'mecanique', ARRAY['étrier AR D'], true),
('Maître-cylindre de frein', 'freinage', 'hydraulique', ARRAY['MC frein'], true),
('Servo-frein', 'freinage', 'assistance', ARRAY['assistance freinage'], true),
('Durite de frein avant gauche', 'freinage', 'hydraulique', ARRAY['flexible frein AV G'], true),
('Durite de frein avant droite', 'freinage', 'hydraulique', ARRAY['flexible frein AV D'], true),
('Durite de frein arrière gauche', 'freinage', 'hydraulique', ARRAY['flexible frein AR G'], false),
('Durite de frein arrière droite', 'freinage', 'hydraulique', ARRAY['flexible frein AR D'], false),
('Câble de frein à main', 'freinage', 'commande', ARRAY['câble frein stationnement'], true),
('Levier de frein à main', 'freinage', 'commande', ARRAY['manette FDM'], true),
('Mâchoires de frein arrière', 'freinage', 'mecanique', ARRAY['garnitures frein AR'], true),
('Tambour de frein arrière gauche', 'freinage', 'mecanique', ARRAY['tambour AR G'], false),
('Tambour de frein arrière droit', 'freinage', 'mecanique', ARRAY['tambour AR D'], false),
('Liquide de frein DOT4', 'freinage', 'fluide', ARRAY['liquide frein'], true),
('Capteur d''usure plaquettes avant', 'freinage', 'mesure', ARRAY['témoin usure AV'], false),
('Capteur d''usure plaquettes arrière', 'freinage', 'mesure', ARRAY['témoin usure AR'], false),
('Capteur ABS avant gauche', 'freinage', 'mesure', ARRAY['capteur roue AV G'], true),
('Capteur ABS avant droit', 'freinage', 'mesure', ARRAY['capteur roue AV D'], true),
('Capteur ABS arrière gauche', 'freinage', 'mesure', ARRAY['capteur roue AR G'], false),
('Capteur ABS arrière droit', 'freinage', 'mesure', ARRAY['capteur roue AR D'], false),
('Bloc hydraulique ABS', 'freinage', 'electronique', ARRAY['groupe ABS'], true),
('Calculateur ABS', 'freinage', 'electronique', ARRAY['ECU ABS'], true),
('Kit de réparation étrier avant', 'freinage', 'reparation', ARRAY['joints étrier AV'], false),
('Kit de réparation étrier arrière', 'freinage', 'reparation', ARRAY['joints étrier AR'], false),
('Piston d''étrier', 'freinage', 'mecanique', ARRAY['piston frein'], false)

ON CONFLICT (name) DO NOTHING;

-- Marquer toutes les pièces populaires importantes
UPDATE public.parts
SET is_popular = true
WHERE name IN (
  'Radiateur moteur',
  'Ventilateur de radiateur',
  'Moteur de ventilateur',
  'Pompe à eau',
  'Thermostat boîtier',
  'Durite supérieure radiateur',
  'Durite inférieure radiateur',
  'Vase d''expansion',
  'Capteur de température liquide',
  'Radiateur chauffage habitacle',
  'Ventilateur chauffage',
  'Résistance de ventilateur chauffage',
  'Pompe à huile',
  'Carter d''huile',
  'Jauge à huile',
  'Bouchon de remplissage huile',
  'Filtre à huile',
  'Refroidisseur d''huile',
  'Capteur de pression d''huile',
  'Joint carter huile',
  'Boîte de vitesses manuelle',
  'Boîte automatique',
  'Convertisseur de couple',
  'Embrayage complet',
  'Disque d''embrayage',
  'Mécanisme d''embrayage',
  'Butée d''embrayage',
  'Butée hydraulique',
  'Récepteur d''embrayage',
  'Émetteur d''embrayage',
  'Câble d''embrayage',
  'Cardan gauche',
  'Cardan droit',
  'Soufflet de cardan intérieur',
  'Soufflet de cardan extérieur',
  'Joint homocinétique intérieur',
  'Joint homocinétique extérieur',
  'Joint spi sortie boîte gauche',
  'Joint spi sortie boîte droit',
  'Support de boîte de vitesses',
  'Levier de vitesses',
  'Huile de boîte manuelle',
  'Huile de boîte automatique',
  'Filtre boîte automatique',
  'Amortisseur avant gauche',
  'Amortisseur avant droit',
  'Ressort hélicoïdal avant gauche',
  'Ressort hélicoïdal avant droit',
  'Coupelle d''amortisseur avant gauche',
  'Coupelle d''amortisseur avant droite',
  'Bras de suspension inférieur gauche',
  'Bras de suspension inférieur droit',
  'Rotule inférieure gauche',
  'Rotule inférieure droite',
  'Biellette de barre stabilisatrice avant gauche',
  'Biellette de barre stabilisatrice avant droite',
  'Barre stabilisatrice avant',
  'Amortisseur arrière gauche',
  'Amortisseur arrière droit',
  'Ressort hélicoïdal arrière gauche',
  'Ressort hélicoïdal arrière droit',
  'Bras de suspension arrière gauche',
  'Bras de suspension arrière droit',
  'Barre stabilisatrice arrière',
  'Crémaillère de direction',
  'Crémaillère assistée électrique',
  'Crémaillère assistée hydraulique',
  'Pompe de direction assistée',
  'Liquide de direction assistée',
  'Soufflet de crémaillère gauche',
  'Soufflet de crémaillère droit',
  'Rotule de direction gauche',
  'Rotule de direction droite',
  'Biellette de direction gauche',
  'Biellette de direction droite',
  'Colonne de direction',
  'Moteur de direction assistée électrique',
  'Disque de frein avant gauche',
  'Disque de frein avant droit',
  'Disque de frein arrière gauche',
  'Disque de frein arrière droit',
  'Plaquettes de frein avant',
  'Plaquettes de frein arrière',
  'Étrier de frein avant gauche',
  'Étrier de frein avant droit',
  'Étrier de frein arrière gauche',
  'Étrier de frein arrière droit',
  'Maître-cylindre de frein',
  'Servo-frein',
  'Durite de frein avant gauche',
  'Durite de frein avant droite',
  'Câble de frein à main',
  'Levier de frein à main',
  'Mâchoires de frein arrière',
  'Liquide de frein DOT4',
  'Capteur ABS avant gauche',
  'Capteur ABS avant droit',
  'Bloc hydraulique ABS',
  'Calculateur ABS'
);
