-- Ajout complet châssis et structure

-- ========================================
-- CHÂSSIS & STRUCTURE
-- ========================================
INSERT INTO public.parts (name, category, subcategory, synonyms, is_popular) VALUES
('Châssis complet', 'carrosserie', 'structure', ARRAY['plateforme'], false),
('Longeron avant gauche', 'carrosserie', 'structure', ARRAY['longeron AV G'], true),
('Longeron avant droit', 'carrosserie', 'structure', ARRAY['longeron AV D'], true),
('Longeron arrière gauche', 'carrosserie', 'structure', ARRAY['longeron AR G'], true),
('Longeron arrière droit', 'carrosserie', 'structure', ARRAY['longeron AR D'], true),
('Traverse avant supérieure', 'carrosserie', 'structure', ARRAY['traverse AV haute'], false),
('Traverse avant inférieure', 'carrosserie', 'structure', ARRAY['traverse AV basse'], false),
('Traverse arrière supérieure', 'carrosserie', 'structure', ARRAY['traverse AR haute'], false),
('Traverse arrière inférieure', 'carrosserie', 'structure', ARRAY['traverse AR basse'], false),
('Berceau moteur', 'carrosserie', 'structure', ARRAY['sous-châssis moteur'], true),
('Traverse de pare-chocs avant', 'carrosserie', 'structure', ARRAY['poutre choc AV'], true),
('Traverse de pare-chocs arrière', 'carrosserie', 'structure', ARRAY['poutre choc AR'], true),
('Plancher avant', 'carrosserie', 'structure', ARRAY['plancher AV'], false),
('Plancher central', 'carrosserie', 'structure', ARRAY['plancher central'], false),
('Plancher arrière', 'carrosserie', 'structure', ARRAY['plancher AR'], false),
('Bas de caisse gauche', 'carrosserie', 'structure', ARRAY['soubassement G'], true),
('Bas de caisse droit', 'carrosserie', 'structure', ARRAY['soubassement D'], true),
('Renfort latéral gauche', 'carrosserie', 'structure', ARRAY['renfort flanc G'], false),
('Renfort latéral droit', 'carrosserie', 'structure', ARRAY['renfort flanc D'], false),
('Pavillon', 'carrosserie', 'structure', ARRAY['toit'], true),
('Montant A gauche', 'carrosserie', 'structure', ARRAY['pied AV G'], false),
('Montant A droit', 'carrosserie', 'structure', ARRAY['pied AV D'], false),
('Montant B gauche', 'carrosserie', 'structure', ARRAY['montant central G'], false),
('Montant B droit', 'carrosserie', 'structure', ARRAY['montant central D'], false),
('Montant C gauche', 'carrosserie', 'structure', ARRAY['montant AR G'], false),
('Montant C droit', 'carrosserie', 'structure', ARRAY['montant AR D'], false),
('Montant D gauche', 'carrosserie', 'structure', ARRAY['montant coffre G'], false),
('Montant D droit', 'carrosserie', 'structure', ARRAY['montant coffre D'], false),
('Tablier avant', 'carrosserie', 'structure', ARRAY['face avant'], true),
('Pare-feu', 'carrosserie', 'structure', ARRAY['cloison moteur'], true),
('Passage de roue avant gauche', 'carrosserie', 'structure', ARRAY['aile intérieure AV G'], true),
('Passage de roue avant droit', 'carrosserie', 'structure', ARRAY['aile intérieure AV D'], true),
('Passage de roue arrière gauche', 'carrosserie', 'structure', ARRAY['aile intérieure AR G'], false),
('Passage de roue arrière droit', 'carrosserie', 'structure', ARRAY['aile intérieure AR D'], false),
('Tunnel central', 'carrosserie', 'structure', ARRAY['tunnel transmission'], false),
('Traverse de coffre', 'carrosserie', 'structure', ARRAY['panneau coffre'], false),
('Sous-bassement avant', 'carrosserie', 'structure', ARRAY['plancher AV inférieur'], false),
('Sous-bassement arrière', 'carrosserie', 'structure', ARRAY['plancher AR inférieur'], false),
('Support radiateur supérieur', 'carrosserie', 'fixation', ARRAY['cadre radiateur haut'], false),
('Support radiateur inférieur', 'carrosserie', 'fixation', ARRAY['cadre radiateur bas'], false),
('Support moteur châssis gauche', 'carrosserie', 'fixation', ARRAY['berceau moteur G'], false),
('Support moteur châssis droit', 'carrosserie', 'fixation', ARRAY['berceau moteur D'], false),
('Support de boîte châssis', 'carrosserie', 'fixation', ARRAY['fixation BV châssis'], false),
('Silentbloc châssis avant gauche', 'carrosserie', 'liaison', ARRAY['silent-bloc châssis AV G'], false),
('Silentbloc châssis avant droit', 'carrosserie', 'liaison', ARRAY['silent-bloc châssis AV D'], false),
('Silentbloc châssis arrière gauche', 'carrosserie', 'liaison', ARRAY['silent-bloc châssis AR G'], false),
('Silentbloc châssis arrière droit', 'carrosserie', 'liaison', ARRAY['silent-bloc châssis AR D'], false),
('Point d''ancrage suspension avant gauche', 'carrosserie', 'fixation', ARRAY['fixation suspension AV G'], false),
('Point d''ancrage suspension avant droit', 'carrosserie', 'fixation', ARRAY['fixation suspension AV D'], false),
('Point d''ancrage suspension arrière gauche', 'carrosserie', 'fixation', ARRAY['fixation suspension AR G'], false),
('Point d''ancrage suspension arrière droit', 'carrosserie', 'fixation', ARRAY['fixation suspension AR D'], false),
('Support amortisseur avant gauche châssis', 'carrosserie', 'fixation', ARRAY['coupelle châssis AV G'], false),
('Support amortisseur avant droit châssis', 'carrosserie', 'fixation', ARRAY['coupelle châssis AV D'], false),
('Support amortisseur arrière gauche châssis', 'carrosserie', 'fixation', ARRAY['coupelle châssis AR G'], false),
('Support amortisseur arrière droit châssis', 'carrosserie', 'fixation', ARRAY['coupelle châssis AR D'], false),
('Support de pare-chocs avant gauche', 'carrosserie', 'fixation', ARRAY['renfort pare-chocs AV G'], false),
('Support de pare-chocs avant droit', 'carrosserie', 'fixation', ARRAY['renfort pare-chocs AV D'], false),
('Support de pare-chocs arrière gauche', 'carrosserie', 'fixation', ARRAY['renfort pare-chocs AR G'], false),
('Support de pare-chocs arrière droit', 'carrosserie', 'fixation', ARRAY['renfort pare-chocs AR D'], false),
('Traverse latérale gauche', 'carrosserie', 'structure', ARRAY['renfort latéral G'], false),
('Traverse latérale droite', 'carrosserie', 'structure', ARRAY['renfort latéral D'], false),
('Support batterie châssis', 'carrosserie', 'fixation', ARRAY['bac batterie'], true),
('Support réservoir', 'carrosserie', 'fixation', ARRAY['sangle réservoir'], true),
('Point d''ancrage ceinture avant gauche', 'carrosserie', 'securite', ARRAY['fixation ceinture AV G'], false),
('Point d''ancrage ceinture avant droit', 'carrosserie', 'securite', ARRAY['fixation ceinture AV D'], false),
('Point d''ancrage ceinture arrière gauche', 'carrosserie', 'securite', ARRAY['fixation ceinture AR G'], false),
('Point d''ancrage ceinture arrière droite', 'carrosserie', 'securite', ARRAY['fixation ceinture AR D'], false),
('Point d''ancrage ceinture arrière centrale', 'carrosserie', 'securite', ARRAY['fixation ceinture AR centre'], false)

ON CONFLICT (name) DO NOTHING;
