-- Ajout des pièces confort, luxe et équipements haut de gamme

-- ========================================
-- CONFORT & LUXE
-- ========================================
INSERT INTO public.parts (name, category, subcategory, synonyms, is_popular) VALUES
('Siège avant gauche électrique', 'interieur', 'sieges', ARRAY['siège conducteur électrique'], true),
('Siège avant droit électrique', 'interieur', 'sieges', ARRAY['siège passager électrique'], true),
('Siège arrière électrique', 'interieur', 'sieges', ARRAY['siège AR électrique'], false),
('Moteur réglage siège avant-arrière', 'interieur', 'confort', ARRAY['moteur longitudinal siège'], false),
('Moteur réglage dossier', 'interieur', 'confort', ARRAY['moteur inclinaison'], false),
('Moteur réglage hauteur siège', 'interieur', 'confort', ARRAY['moteur hauteur'], false),
('Moteur réglage lombaire', 'interieur', 'confort', ARRAY['moteur soutien lombaire'], false),
('Moteur réglage appui-tête', 'interieur', 'confort', ARRAY['moteur têtière'], false),
('Mémoire de siège', 'interieur', 'confort', ARRAY['module mémoire siège'], false),
('Siège chauffant avant gauche', 'interieur', 'confort', ARRAY['chauffage siège AV G'], true),
('Siège chauffant avant droit', 'interieur', 'confort', ARRAY['chauffage siège AV D'], true),
('Siège chauffant arrière', 'interieur', 'confort', ARRAY['chauffage siège AR'], false),
('Siège ventilé avant gauche', 'interieur', 'confort', ARRAY['ventilation siège AV G'], false),
('Siège ventilé avant droit', 'interieur', 'confort', ARRAY['ventilation siège AV D'], false),
('Siège massant avant gauche', 'interieur', 'confort', ARRAY['massage siège AV G'], false),
('Siège massant avant droit', 'interieur', 'confort', ARRAY['massage siège AV D'], false),
('Compresseur massage siège', 'interieur', 'confort', ARRAY['pompe massage'], false),
('Volant chauffant', 'interieur', 'confort', ARRAY['chauffage volant'], true),
('Résistance volant chauffant', 'interieur', 'confort', ARRAY['élément chauffant volant'], false),
('Volant réglable électrique', 'interieur', 'confort', ARRAY['volant électrique'], false),
('Volant multifonction', 'interieur', 'commande', ARRAY['volant commandes'], true),
('Airbag volant', 'interieur', 'securite', ARRAY['coussin gonflable volant'], true),
('Console centrale réfrigérée', 'interieur', 'confort', ARRAY['glacière console'], false),
('Éclairage d''ambiance RGB', 'interieur', 'confort', ARRAY['LED ambiance couleur'], false),
('Module éclairage ambiance', 'interieur', 'confort', ARRAY['contrôleur LED'], false),
('Rideau pare-soleil électrique', 'interieur', 'confort', ARRAY['store électrique'], false),
('Pare-soleil arrière électrique', 'interieur', 'confort', ARRAY['store lunette AR'], false),
('Toit panoramique', 'vitrage', 'confort', ARRAY['toit vitré'], true),
('Moteur toit ouvrant', 'vitrage', 'confort', ARRAY['mécanisme sunroof'], true),
('Store toit panoramique', 'interieur', 'confort', ARRAY['rideau toit'], false),
('Hayon électrique', 'carrosserie', 'confort', ARRAY['coffre électrique'], true),
('Moteur hayon électrique', 'carrosserie', 'confort', ARRAY['actionneur coffre'], true),
('Portes électriques', 'carrosserie', 'confort', ARRAY['portes automatiques'], false),
('Marche-pied électrique', 'carrosserie', 'confort', ARRAY['marchepied rétractable'], false),
('Rétroviseurs rabattables électriques', 'carrosserie', 'confort', ARRAY['rétros électriques'], true),
('Attelage escamotable électrique', 'accessoires', 'confort', ARRAY['attelage rétractable'], false),
('Système audio haut de gamme', 'electronique', 'multimedia', ARRAY['sono premium'], true),
('Amplificateur premium', 'electronique', 'audio', ARRAY['ampli hifi'], false),
('Caisson de basses premium', 'electronique', 'audio', ARRAY['subwoofer premium'], false),
('Haut-parleurs premium', 'electronique', 'audio', ARRAY['HP haut de gamme'], false),
('Écran passager', 'electronique', 'multimedia', ARRAY['écran secondaire'], false),
('Écrans appui-tête', 'electronique', 'multimedia', ARRAY['écrans AR'], false),
('Console multimédia arrière', 'electronique', 'multimedia', ARRAY['commandes AR'], false),
('Tablettes arrière', 'interieur', 'confort', ARRAY['tablettes repliables'], false),
('Accoudoir central avant', 'interieur', 'confort', ARRAY['repose-bras AV'], true),
('Accoudoir central arrière', 'interieur', 'confort', ARRAY['repose-bras AR'], false),
('Repose-pieds passager', 'interieur', 'confort', ARRAY['cale-pied'], false),
('Porte-gobelets réfrigéré', 'interieur', 'confort', ARRAY['porte-verre chauffant'], false),
('Purificateur d''air habitacle', 'climatisation', 'confort', ARRAY['ioniseur'], false),
('Parfum d''ambiance automatique', 'interieur', 'confort', ARRAY['diffuseur parfum'], false),
('Chauffage stationnaire', 'climatisation', 'confort', ARRAY['webasto'], false),
('Climatisation 4 zones', 'climatisation', 'confort', ARRAY['clim multizone'], false),
('Diffuseur air arrière', 'climatisation', 'confort', ARRAY['bouches AR'], false),
('Commande climatisation arrière', 'climatisation', 'confort', ARRAY['réglage clim AR'], false)

ON CONFLICT (name) DO NOTHING;
