-- Ajout des consommables, fluides et produits d'entretien

-- ========================================
-- CONSOMMABLES & FLUIDES
-- ========================================
INSERT INTO public.parts (name, category, subcategory, synonyms, is_popular) VALUES
('Huile moteur 0W20', 'moteur', 'fluide', ARRAY['huile 0W20'], true),
('Huile moteur 0W30', 'moteur', 'fluide', ARRAY['huile 0W30'], true),
('Huile moteur 5W20', 'moteur', 'fluide', ARRAY['huile 5W20'], false),
('Huile moteur 10W30', 'moteur', 'fluide', ARRAY['huile 10W30'], false),
('Huile moteur 15W40', 'moteur', 'fluide', ARRAY['huile 15W40'], true),
('Huile moteur 20W50', 'moteur', 'fluide', ARRAY['huile 20W50'], false),
('Huile synthèse', 'moteur', 'fluide', ARRAY['huile 100% synthèse'], true),
('Huile semi-synthèse', 'moteur', 'fluide', ARRAY['huile semi-synthèse'], true),
('Huile minérale', 'moteur', 'fluide', ARRAY['huile minérale'], false),
('Huile longlife', 'moteur', 'fluide', ARRAY['huile longue durée'], true),
('Additif huile moteur', 'moteur', 'additif', ARRAY['traitement huile'], false),
('Nettoyant moteur', 'moteur', 'entretien', ARRAY['flush moteur'], false),
('Liquide refroidissement rouge', 'moteur', 'fluide', ARRAY['antigel rouge'], true),
('Liquide refroidissement vert', 'moteur', 'fluide', ARRAY['antigel vert'], true),
('Liquide refroidissement bleu', 'moteur', 'fluide', ARRAY['antigel bleu'], true),
('Liquide refroidissement rose', 'moteur', 'fluide', ARRAY['antigel rose'], false),
('Antigel concentré', 'moteur', 'fluide', ARRAY['liquide refroidissement concentré'], true),
('Additif radiateur', 'moteur', 'additif', ARRAY['stop fuite radiateur'], false),
('Liquide de frein DOT 3', 'freinage', 'fluide', ARRAY['DOT3'], true),
('Liquide de frein DOT 4', 'freinage', 'fluide', ARRAY['DOT4'], true),
('Liquide de frein DOT 5.1', 'freinage', 'fluide', ARRAY['DOT 5.1'], false),
('Graisse de frein', 'freinage', 'lubrifiant', ARRAY['pâte frein'], false),
('Nettoyant freins', 'freinage', 'entretien', ARRAY['dégraissant freins'], true),
('Huile de boîte 75W80', 'transmission', 'fluide', ARRAY['huile BV 75W80'], true),
('Huile de boîte 75W90', 'transmission', 'fluide', ARRAY['huile BV 75W90'], true),
('Huile de boîte 80W90', 'transmission', 'fluide', ARRAY['huile BV 80W90'], false),
('Huile ATF Dexron III', 'transmission', 'fluide', ARRAY['ATF DIII'], true),
('Huile ATF Dexron VI', 'transmission', 'fluide', ARRAY['ATF DVI'], true),
('Huile de pont', 'transmission', 'fluide', ARRAY['huile différentiel'], true),
('Additif boîte automatique', 'transmission', 'additif', ARRAY['traitement BVA'], false),
('Liquide LHM vert', 'suspension', 'fluide', ARRAY['LHM'], false),
('Liquide direction assistée', 'direction', 'fluide', ARRAY['huile DA'], true),
('Graisse de roulement', 'suspension', 'lubrifiant', ARRAY['graisse palier'], true),
('Graisse multi-usage', 'accessoires', 'lubrifiant', ARRAY['graisse lithium'], true),
('Graisse cuivre', 'accessoires', 'lubrifiant', ARRAY['pâte cuivre'], true),
('Graisse hautes températures', 'accessoires', 'lubrifiant', ARRAY['graisse HT'], false),
('Liquide lave-glace été', 'electricite', 'fluide', ARRAY['lave-glace été'], true),
('Liquide lave-glace hiver -20°', 'electricite', 'fluide', ARRAY['antigel lave-glace'], true),
('Liquide lave-glace hiver -30°', 'electricite', 'fluide', ARRAY['antigel extrême'], false),
('Gaz climatisation R134a', 'climatisation', 'fluide', ARRAY['gaz clim R134a'], true),
('Gaz climatisation R1234yf', 'climatisation', 'fluide', ARRAY['gaz clim R1234yf'], true),
('Huile compresseur climatisation', 'climatisation', 'fluide', ARRAY['huile PAG'], false),
('Additif climatisation', 'climatisation', 'additif', ARRAY['stop fuite clim'], false),
('AdBlue 5L', 'carburant', 'additif', ARRAY['urée 5 litres'], true),
('AdBlue 10L', 'carburant', 'additif', ARRAY['urée 10 litres'], true),
('AdBlue 20L', 'carburant', 'additif', ARRAY['urée 20 litres'], false),
('Additif gasoil hiver', 'carburant', 'additif', ARRAY['anti-gel diesel'], true),
('Additif gasoil nettoyant', 'carburant', 'additif', ARRAY['nettoyant injecteurs diesel'], false),
('Additif essence nettoyant', 'carburant', 'additif', ARRAY['nettoyant injecteurs essence'], false),
('Octane booster', 'carburant', 'additif', ARRAY['additif octane'], false),
('Super éthanol E85', 'carburant', 'carburant', ARRAY['bioéthanol'], false),
('Additif FAP', 'echappement', 'additif', ARRAY['cérine FAP'], false),
('WD40 spray', 'accessoires', 'entretien', ARRAY['dégrippant'], true),
('Dégrippant multifonction', 'accessoires', 'entretien', ARRAY['lubrifiant pénétrant'], true),
('Nettoyant contact électrique', 'electricite', 'entretien', ARRAY['nettoyant électronique'], false),
('Graisse diélectrique', 'electricite', 'lubrifiant', ARRAY['graisse contacts'], false),
('Silicone spray', 'accessoires', 'entretien', ARRAY['lubrifiant silicone'], true),
('Dégraissant moteur', 'moteur', 'entretien', ARRAY['nettoyant moteur externe'], true),
('Polish carrosserie', 'carrosserie', 'entretien', ARRAY['pâte à polir'], true),
('Cire carrosserie', 'carrosserie', 'entretien', ARRAY['wax'], true),
('Shampoing voiture', 'carrosserie', 'entretien', ARRAY['savon auto'], true),
('Rénovateur plastique', 'carrosserie', 'entretien', ARRAY['rénovateur noir'], true),
('Nettoyant jantes', 'roues', 'entretien', ARRAY['dégraissant jantes'], true),
('Nettoyant tableau de bord', 'interieur', 'entretien', ARRAY['polish plastique'], true),
('Nettoyant tissu', 'interieur', 'entretien', ARRAY['shampooing sièges'], true),
('Nettoyant cuir', 'interieur', 'entretien', ARRAY['savon cuir'], true),
('Crème cuir', 'interieur', 'entretien', ARRAY['baume cuir'], true),
('Désodorisant habitacle', 'interieur', 'entretien', ARRAY['parfum voiture'], true),
('Anti-buée', 'vitrage', 'entretien', ARRAY['spray anti-buée'], false),
('Nettoyant vitres', 'vitrage', 'entretien', ARRAY['lave-vitre'], true),
('Traitement hydrophobe', 'vitrage', 'entretien', ARRAY['rain repellent'], false),
('Joint liquide', 'moteur', 'etancheite', ARRAY['pâte à joint'], true),
('Silicone haute température', 'moteur', 'etancheite', ARRAY['silicone RTV'], false),
('Frein filet', 'accessoires', 'fixation', ARRAY['loctite'], true),
('Colle anaérobie', 'accessoires', 'fixation', ARRAY['loctite forte'], false),
('Mastic pare-brise', 'carrosserie', 'etancheite', ARRAY['colle pare-brise'], false),
('Mastic carrosserie', 'carrosserie', 'reparation', ARRAY['mastic polyester'], false),
('Apprêt carrosserie', 'carrosserie', 'peinture', ARRAY['primer'], false),
('Peinture carrosserie', 'carrosserie', 'peinture', ARRAY['peinture auto'], false),
('Vernis carrosserie', 'carrosserie', 'peinture', ARRAY['clear coat'], false),
('Anti-rouille', 'carrosserie', 'protection', ARRAY['traitement antirouille'], true),
('Protection soubassement', 'carrosserie', 'protection', ARRAY['traitement chassis'], false)

ON CONFLICT (name) DO NOTHING;
