-- Ajout des pièces de sécurité, électronique, décoration et structure intérieure

-- ========================================
-- SÉCURITÉ (ceintures et airbags)
-- ========================================
INSERT INTO public.parts (name, category, subcategory, synonyms, is_popular) VALUES
('Ceinture de sécurité avant gauche', 'interieur', 'securite', ARRAY['ceinture AV G'], true),
('Ceinture de sécurité avant droite', 'interieur', 'securite', ARRAY['ceinture AV D'], true),
('Ceinture de sécurité arrière gauche', 'interieur', 'securite', ARRAY['ceinture AR G'], false),
('Ceinture de sécurité arrière droite', 'interieur', 'securite', ARRAY['ceinture AR D'], false),
('Ceinture de sécurité arrière centrale', 'interieur', 'securite', ARRAY['ceinture AR centrale'], false),
('Enrouleur de ceinture avant gauche', 'interieur', 'securite', ARRAY['enrouleur AV G'], true),
('Enrouleur de ceinture avant droit', 'interieur', 'securite', ARRAY['enrouleur AV D'], true),
('Enrouleur de ceinture arrière', 'interieur', 'securite', ARRAY['enrouleur AR'], false),
('Prétensionneur de ceinture avant gauche', 'interieur', 'securite', ARRAY['prétensionneur AV G'], true),
('Prétensionneur de ceinture avant droit', 'interieur', 'securite', ARRAY['prétensionneur AV D'], true),
('Boucle de ceinture avant gauche', 'interieur', 'securite', ARRAY['boucle AV G'], false),
('Boucle de ceinture avant droite', 'interieur', 'securite', ARRAY['boucle AV D'], false),
('Boucle de ceinture arrière', 'interieur', 'securite', ARRAY['boucle AR'], false),
('Ancrage ISOFIX gauche', 'interieur', 'securite', ARRAY['ISOFIX G'], true),
('Ancrage ISOFIX droit', 'interieur', 'securite', ARRAY['ISOFIX D'], true),
('Ancrage ISOFIX central', 'interieur', 'securite', ARRAY['ISOFIX centre'], false),
('Airbag frontal conducteur', 'interieur', 'securite', ARRAY['airbag volant'], true),
('Airbag frontal passager', 'interieur', 'securite', ARRAY['airbag tableau de bord'], true),
('Airbag latéral avant gauche', 'interieur', 'securite', ARRAY['airbag siège AV G'], true),
('Airbag latéral avant droit', 'interieur', 'securite', ARRAY['airbag siège AV D'], true),
('Airbag latéral arrière gauche', 'interieur', 'securite', ARRAY['airbag siège AR G'], false),
('Airbag latéral arrière droit', 'interieur', 'securite', ARRAY['airbag siège AR D'], false),
('Airbag rideau gauche', 'interieur', 'securite', ARRAY['airbag tête G'], true),
('Airbag rideau droit', 'interieur', 'securite', ARRAY['airbag tête D'], true),
('Airbag de genoux', 'interieur', 'securite', ARRAY['airbag conducteur bas'], false),
('Capteur d''impact avant gauche', 'interieur', 'securite', ARRAY['capteur choc AV G'], false),
('Capteur d''impact avant droit', 'interieur', 'securite', ARRAY['capteur choc AV D'], false),
('Capteur d''impact latéral gauche', 'interieur', 'securite', ARRAY['capteur choc lat G'], false),
('Capteur d''impact latéral droit', 'interieur', 'securite', ARRAY['capteur choc lat D'], false),
('Calculateur d''airbag', 'interieur', 'securite', ARRAY['ECU airbag', 'module airbag'], true),
('Témoin airbag', 'interieur', 'securite', ARRAY['voyant airbag'], false),
('Contacteur tournant airbag', 'interieur', 'securite', ARRAY['spirale airbag'], true),
('Faisceau airbag', 'interieur', 'securite', ARRAY['câblage airbag'], false),

-- ========================================
-- ÉLECTRONIQUE & COMMANDES (faisceaux et modules)
-- ========================================
('Faisceau habitacle principal', 'electronique', 'cablage', ARRAY['faisceau électrique habitacle'], true),
('Faisceau tableau de bord', 'electronique', 'cablage', ARRAY['faisceau TB'], true),
('Faisceau porte avant gauche', 'electronique', 'cablage', ARRAY['faisceau porte AV G'], false),
('Faisceau porte avant droite', 'electronique', 'cablage', ARRAY['faisceau porte AV D'], false),
('Faisceau porte arrière gauche', 'electronique', 'cablage', ARRAY['faisceau porte AR G'], false),
('Faisceau porte arrière droite', 'electronique', 'cablage', ARRAY['faisceau porte AR D'], false),
('Faisceau de toit', 'electronique', 'cablage', ARRAY['faisceau plafonnier'], false),
('Faisceau de sièges avant', 'electronique', 'cablage', ARRAY['faisceau sièges AV'], false),
('Faisceau de sièges arrière', 'electronique', 'cablage', ARRAY['faisceau sièges AR'], false),
('Connecteur multibroches', 'electronique', 'connexion', ARRAY['prise électrique'], false),
('Boîtier de jonction électrique', 'electronique', 'distribution', ARRAY['boîte jonction'], false),
('Boîtier de relais habitacle', 'electronique', 'distribution', ARRAY['boîte relais intérieur'], true),
('Relais de climatisation', 'electronique', 'commande', ARRAY['relais clim'], false),
('Relais de dégivrage', 'electronique', 'commande', ARRAY['relais lunette AR'], false),
('Module de confort', 'electronique', 'gestion', ARRAY['BCM', 'UCH'], true),
('Module de climatisation automatique', 'electronique', 'climatisation', ARRAY['calculateur clim auto'], true),
('Module d''airbag central', 'electronique', 'securite', ARRAY['centrale airbag'], true),
('Module de porte avant gauche', 'electronique', 'confort', ARRAY['module porte AV G'], false),
('Module de porte avant droite', 'electronique', 'confort', ARRAY['module porte AV D'], false),
('Interrupteur de feux', 'electronique', 'commande', ARRAY['commande éclairage'], true),
('Interrupteur de feux de détresse', 'electronique', 'commande', ARRAY['bouton warning'], true),
('Interrupteur de dégivrage lunette', 'electronique', 'commande', ARRAY['bouton dégivrage AR'], true),
('Interrupteur de dégivrage rétroviseurs', 'electronique', 'commande', ARRAY['bouton dégivrage rétros'], false),
('Bouton mode conduite', 'electronique', 'commande', ARRAY['sélecteur mode'], false),
('Bouton Start-Stop', 'electronique', 'commande', ARRAY['bouton démarrage'], true),
('Commande d''éclairage d''ambiance', 'electronique', 'confort', ARRAY['bouton LED ambiance'], false),
('Commande de toit ouvrant', 'electronique', 'confort', ARRAY['bouton sunroof'], false),
('Capteur de luminosité habitacle', 'electronique', 'confort', ARRAY['cellule lumière'], true),
('Capteur de température intérieure', 'electronique', 'climatisation', ARRAY['sonde température habitacle'], true),
('Capteur de pluie et luminosité', 'electronique', 'confort', ARRAY['capteur combiné'], true),
('Capteur de présence passager', 'electronique', 'securite', ARRAY['capteur occupation siège'], true),
('Commande de siège chauffant gauche', 'electronique', 'confort', ARRAY['bouton chauffage siège G'], false),
('Commande de siège chauffant droit', 'electronique', 'confort', ARRAY['bouton chauffage siège D'], false),
('Commande de volant chauffant', 'electronique', 'confort', ARRAY['bouton chauffage volant'], false),
('Commande de ventilation de siège', 'electronique', 'confort', ARRAY['bouton ventilation siège'], false),
('Potentiomètre d''éclairage', 'electronique', 'commande', ARRAY['variateur luminosité'], false),

-- ========================================
-- DÉCORATION & FINITION
-- ========================================
('Insert décoratif bois tableau de bord', 'interieur', 'decoration', ARRAY['garniture bois TB'], false),
('Insert décoratif aluminium', 'interieur', 'decoration', ARRAY['garniture alu'], false),
('Insert décoratif carbone', 'interieur', 'decoration', ARRAY['garniture carbone'], false),
('Insert décoratif piano black', 'interieur', 'decoration', ARRAY['garniture noir brillant'], false),
('Insert décoratif porte gauche', 'interieur', 'decoration', ARRAY['garniture déco porte G'], false),
('Insert décoratif porte droite', 'interieur', 'decoration', ARRAY['garniture déco porte D'], false),
('Contour d''aérateur central', 'interieur', 'decoration', ARRAY['cerclage aérateur'], false),
('Contour d''aérateur latéral', 'interieur', 'decoration', ARRAY['cerclage bouche air'], false),
('Contour de levier de vitesse', 'interieur', 'decoration', ARRAY['cerclage levier'], false),
('Contour de frein à main', 'interieur', 'decoration', ARRAY['cerclage frein main'], false),
('Enjoliveur console centrale', 'interieur', 'decoration', ARRAY['habillage console'], false),
('Enjoliveur de commande centrale', 'interieur', 'decoration', ARRAY['cadre commandes'], false),
('Badge intérieur', 'interieur', 'decoration', ARRAY['logo habitacle'], false),
('Monogramme de console', 'interieur', 'decoration', ARRAY['sigle intérieur'], false),
('Éclairage d''ambiance LED avant', 'interieur', 'confort', ARRAY['LED ambiance AV'], false),
('Éclairage d''ambiance LED arrière', 'interieur', 'confort', ARRAY['LED ambiance AR'], false),
('Bande LED de portière', 'interieur', 'decoration', ARRAY['LED porte'], false),
('Contour de porte chromé', 'interieur', 'decoration', ARRAY['liseré chrome porte'], false),
('Enjoliveur de poignée intérieure', 'interieur', 'decoration', ARRAY['contour poignée'], false),
('Enjoliveur de bouton de lève-vitre', 'interieur', 'decoration', ARRAY['cadre bouton vitre'], false),
('Cache vis de garniture tableau de bord', 'interieur', 'habillage', ARRAY['bouchon vis TB'], false),
('Cache vis de garniture porte', 'interieur', 'habillage', ARRAY['bouchon vis porte'], false),
('Plaque de seuil aluminium', 'interieur', 'decoration', ARRAY['seuil alu'], false),
('Plaque de seuil éclairée', 'interieur', 'decoration', ARRAY['seuil LED'], false),

-- ========================================
-- ISOLATION / STRUCTURE / FIXATIONS
-- ========================================
('Isolation phonique plancher avant', 'interieur', 'isolation', ARRAY['insonorisation plancher AV'], false),
('Isolation phonique plancher arrière', 'interieur', 'isolation', ARRAY['insonorisation plancher AR'], false),
('Isolation phonique tableau de bord', 'interieur', 'isolation', ARRAY['insonorisation TB'], false),
('Isolation phonique de porte avant gauche', 'interieur', 'isolation', ARRAY['insonorisation porte AV G'], false),
('Isolation phonique de porte avant droite', 'interieur', 'isolation', ARRAY['insonorisation porte AV D'], false),
('Isolation phonique tunnel central', 'interieur', 'isolation', ARRAY['insonorisation tunnel'], false),
('Isolation thermique pare-feu', 'interieur', 'isolation', ARRAY['isolant pare-feu'], true),
('Isolation thermique de toit', 'interieur', 'isolation', ARRAY['isolant pavillon'], false),
('Joint d''étanchéité central habitacle', 'interieur', 'etancheite', ARRAY['joint plancher'], false),
('Joint de passage câble', 'interieur', 'etancheite', ARRAY['passe-fil'], false),
('Agrafe plastique de garniture', 'interieur', 'fixation', ARRAY['clip garniture'], false),
('Clip de panneau de porte', 'interieur', 'fixation', ARRAY['agrafe panneau'], false),
('Clip de montant', 'interieur', 'fixation', ARRAY['agrafe montant'], false),
('Clip de ciel de toit', 'interieur', 'fixation', ARRAY['agrafe pavillon'], false),
('Visserie de fixation siège avant', 'interieur', 'fixation', ARRAY['boulons siège AV'], true),
('Visserie de fixation siège arrière', 'interieur', 'fixation', ARRAY['boulons siège AR'], false),
('Visserie de garniture de porte', 'interieur', 'fixation', ARRAY['vis panneau porte'], false),
('Visserie de tableau de bord', 'interieur', 'fixation', ARRAY['vis TB'], false),
('Clip de tableau de bord', 'interieur', 'fixation', ARRAY['agrafe TB'], false),
('Clip de console centrale', 'interieur', 'fixation', ARRAY['agrafe console'], false),
('Support d''aérateur central', 'interieur', 'fixation', ARRAY['fixation aérateur'], false),
('Support d''aérateur latéral', 'interieur', 'fixation', ARRAY['fixation bouche air'], false),
('Support de module airbag passager', 'interieur', 'fixation', ARRAY['fixation airbag TB'], false),
('Support de console centrale', 'interieur', 'fixation', ARRAY['fixation console'], false),
('Support de plafonnier avant', 'interieur', 'fixation', ARRAY['fixation plafonnier AV'], false),
('Support de plafonnier arrière', 'interieur', 'fixation', ARRAY['fixation plafonnier AR'], false),
('Support de pédalier', 'interieur', 'fixation', ARRAY['fixation pédales'], true),
('Support de boîte à gants', 'interieur', 'fixation', ARRAY['fixation vide-poche'], false),
('Renfort de tableau de bord', 'interieur', 'structure', ARRAY['armature TB'], false),
('Traverse de tableau de bord', 'interieur', 'structure', ARRAY['poutre TB'], true),
('Structure de console centrale', 'interieur', 'structure', ARRAY['châssis console'], false),

-- ========================================
-- COMPLÉMENTS ÉLECTRONIQUE INTÉRIEUR
-- ========================================
('Prise USB avant', 'electronique', 'multimedia', ARRAY['port USB AV'], true),
('Prise USB arrière', 'electronique', 'multimedia', ARRAY['port USB AR'], true),
('Prise 12V avant', 'electronique', 'accessoire', ARRAY['allume-cigare AV'], true),
('Prise 12V arrière', 'electronique', 'accessoire', ARRAY['allume-cigare AR'], false),
('Prise 220V inverseur', 'electronique', 'accessoire', ARRAY['prise secteur'], false),
('Module de charge sans fil', 'electronique', 'multimedia', ARRAY['chargeur induction'], true),
('Amplificateur audio', 'electronique', 'audio', ARRAY['ampli système son'], false),
('Caisson de basses', 'electronique', 'audio', ARRAY['subwoofer'], false),
('Tweeter avant gauche', 'electronique', 'audio', ARRAY['HP aigu AV G'], false),
('Tweeter avant droit', 'electronique', 'audio', ARRAY['HP aigu AV D'], false),
('Haut-parleur de porte avant gauche', 'electronique', 'audio', ARRAY['HP porte AV G'], false),
('Haut-parleur de porte avant droite', 'electronique', 'audio', ARRAY['HP porte AV D'], false),
('Haut-parleur de porte arrière gauche', 'electronique', 'audio', ARRAY['HP porte AR G'], false),
('Haut-parleur de porte arrière droite', 'electronique', 'audio', ARRAY['HP porte AR D'], false),

-- ========================================
-- COMPLÉMENTS CONFORT
-- ========================================
('Résistance de siège chauffant avant gauche', 'interieur', 'confort', ARRAY['élément chauffant siège AV G'], false),
('Résistance de siège chauffant avant droit', 'interieur', 'confort', ARRAY['élément chauffant siège AV D'], false),
('Résistance de siège chauffant arrière', 'interieur', 'confort', ARRAY['élément chauffant siège AR'], false),
('Résistance de volant chauffant', 'interieur', 'confort', ARRAY['élément chauffant volant'], false),
('Ventilateur de siège avant gauche', 'interieur', 'confort', ARRAY['ventilation siège AV G'], false),
('Ventilateur de siège avant droit', 'interieur', 'confort', ARRAY['ventilation siège AV D'], false),
('Moteur de réglage lombaire gauche', 'interieur', 'confort', ARRAY['actionneur lombaire G'], false),
('Moteur de réglage lombaire droit', 'interieur', 'confort', ARRAY['actionneur lombaire D'], false),
('Compresseur de massage de siège', 'interieur', 'confort', ARRAY['pompe massage'], false),
('Module de massage avant gauche', 'interieur', 'confort', ARRAY['massage siège G'], false),
('Module de massage avant droit', 'interieur', 'confort', ARRAY['massage siège D'], false)

ON CONFLICT (name) DO NOTHING;

-- Marquer les pièces populaires
UPDATE public.parts
SET is_popular = true
WHERE name IN (
  'Ceinture de sécurité avant gauche',
  'Ceinture de sécurité avant droite',
  'Enrouleur de ceinture avant gauche',
  'Enrouleur de ceinture avant droit',
  'Prétensionneur de ceinture avant gauche',
  'Prétensionneur de ceinture avant droit',
  'Ancrage ISOFIX gauche',
  'Ancrage ISOFIX droit',
  'Airbag frontal conducteur',
  'Airbag frontal passager',
  'Airbag latéral avant gauche',
  'Airbag latéral avant droit',
  'Airbag rideau gauche',
  'Airbag rideau droit',
  'Calculateur d''airbag',
  'Contacteur tournant airbag',
  'Faisceau habitacle principal',
  'Faisceau tableau de bord',
  'Boîtier de relais habitacle',
  'Module de confort',
  'Module de climatisation automatique',
  'Module d''airbag central',
  'Interrupteur de feux',
  'Interrupteur de feux de détresse',
  'Interrupteur de dégivrage lunette',
  'Bouton Start-Stop',
  'Capteur de luminosité habitacle',
  'Capteur de température intérieure',
  'Capteur de pluie et luminosité',
  'Capteur de présence passager',
  'Isolation thermique pare-feu',
  'Visserie de fixation siège avant',
  'Support de pédalier',
  'Traverse de tableau de bord',
  'Prise USB avant',
  'Prise USB arrière',
  'Prise 12V avant',
  'Module de charge sans fil'
);
