-- Ajout massif final de toutes les pièces manquantes

-- ========================================
-- REFROIDISSEMENT (ultra complet)
-- ========================================
INSERT INTO public.parts (name, category, subcategory, synonyms, is_popular) VALUES
('Calandre de radiateur', 'moteur', 'refroidissement', ARRAY['cadre radiateur'], false),
('Durite de radiateur supérieure', 'moteur', 'refroidissement', ARRAY['durite haute'], true),
('Durite de radiateur inférieure', 'moteur', 'refroidissement', ARRAY['durite basse'], true),
('Durite de chauffage aller', 'moteur', 'refroidissement', ARRAY['durite chauffage entrée'], false),
('Durite de chauffage retour', 'moteur', 'refroidissement', ARRAY['durite chauffage sortie'], false),
('Électrovanne de thermostat', 'moteur', 'refroidissement', ARRAY['valve thermostat électrique'], false),
('Liquide de refroidissement', 'moteur', 'fluide', ARRAY['antigel'], true),
('Purgeur de radiateur', 'moteur', 'refroidissement', ARRAY['vis de purge radiateur'], false),
('Radiateur d''huile moteur', 'moteur', 'lubrification', ARRAY['échangeur huile'], true),
('Radiateur principal', 'moteur', 'refroidissement', ARRAY['radiateur moteur'], true),
('Support de radiateur supérieur', 'moteur', 'fixation', ARRAY['fixation radiateur haut'], false),
('Support de radiateur inférieur', 'moteur', 'fixation', ARRAY['fixation radiateur bas'], false),
('Thermostat d''eau', 'moteur', 'refroidissement', ARRAY['calorstat'], true),
('Ventilateur de radiateur électrique', 'moteur', 'refroidissement', ARRAY['motoventilateur'], true),
('Ventilateur de radiateur auxiliaire', 'moteur', 'refroidissement', ARRAY['ventilateur additionnel'], false),
('Résistance de ventilateur', 'moteur', 'refroidissement', ARRAY['régulateur ventilateur'], false),

-- ========================================
-- LUBRIFICATION (détaillé)
-- ========================================
('Carter d''huile aluminium', 'moteur', 'lubrification', ARRAY['carter alu'], true),
('Carter d''huile acier', 'moteur', 'lubrification', ARRAY['carter tôle'], false),
('Crépine de pompe à huile', 'moteur', 'lubrification', ARRAY['tamis huile'], false),
('Filtre à huile cartouche', 'moteur', 'filtration', ARRAY['filtre huile papier'], true),
('Filtre à huile vissable', 'moteur', 'filtration', ARRAY['filtre huile à visser'], true),
('Huile moteur 5W30', 'moteur', 'fluide', ARRAY['huile 5W30'], true),
('Huile moteur 5W40', 'moteur', 'fluide', ARRAY['huile 5W40'], true),
('Huile moteur 10W40', 'moteur', 'fluide', ARRAY['huile 10W40'], true),
('Joint de bouchon de vidange', 'moteur', 'etancheite', ARRAY['joint vidange'], true),
('Niveau d''huile électronique', 'moteur', 'mesure', ARRAY['capteur niveau huile'], false),
('Tube de jauge d''huile', 'moteur', 'mesure', ARRAY['guide jauge'], false),

-- ========================================
-- ADMISSION D''AIR (complet)
-- ========================================
('Boîtier de filtre à air', 'moteur', 'admission', ARRAY['boîte air'], true),
('Clapet de papillon', 'moteur', 'admission', ARRAY['volet papillon'], false),
('Couvercle de boîte à air', 'moteur', 'admission', ARRAY['couvercle filtre air'], false),
('Débitmètre de masse d''air', 'moteur', 'mesure', ARRAY['MAF sensor'], true),
('Filtre à air sport', 'moteur', 'performance', ARRAY['filtre KN'], false),
('Gaine d''admission', 'moteur', 'admission', ARRAY['manche air'], false),
('Manchon d''admission', 'moteur', 'admission', ARRAY['durite souple admission'], false),
('Papillon des gaz motorisé', 'moteur', 'admission', ARRAY['boîtier papillon électrique'], true),
('Prise d''air dynamique', 'moteur', 'admission', ARRAY['snorkel'], false),
('Résonateur d''admission', 'moteur', 'admission', ARRAY['boîte résonance'], false),
('Sonde de température d''air', 'moteur', 'mesure', ARRAY['capteur température admission'], false),

-- ========================================
-- TURBO & SURALIMENTATION (très détaillé)
-- ========================================
('Actuateur de turbo', 'moteur', 'turbo', ARRAY['capsule pneumatique'], false),
('Carter de turbo', 'moteur', 'turbo', ARRAY['corps turbo'], false),
('Coude d''échappement turbo', 'moteur', 'turbo', ARRAY['collecteur turbo'], false),
('Durite d''huile turbo aller', 'moteur', 'turbo', ARRAY['tuyau graissage turbo'], false),
('Joint de turbine', 'moteur', 'turbo', ARRAY['joint corps turbo'], false),
('Kit de réparation turbo', 'moteur', 'turbo', ARRAY['kit joints turbo'], false),
('Roulement de turbo', 'moteur', 'turbo', ARRAY['palier turbo'], false),
('Turbine de turbocompresseur', 'moteur', 'turbo', ARRAY['roue turbine'], false),
('Turbocompresseur complet', 'moteur', 'turbo', ARRAY['turbo'], true),
('Turbocompresseur bi-turbo', 'moteur', 'turbo', ARRAY['double turbo'], false),
('Turbocompresseur géométrie variable', 'moteur', 'turbo', ARRAY['VGT'], true),
('Valve de décharge externe', 'moteur', 'turbo', ARRAY['wastegate externe'], false),
('Valve de décharge interne', 'moteur', 'turbo', ARRAY['wastegate interne'], false),

-- ========================================
-- CARROSSERIE SPÉCIFIQUE (détails finaux)
-- ========================================
('Absorbeur de chocs avant', 'carrosserie', 'securite', ARRAY['poutre choc AV'], true),
('Absorbeur de chocs arrière', 'carrosserie', 'securite', ARRAY['poutre choc AR'], true),
('Baguette de protection latérale droite', 'carrosserie', 'protection', ARRAY['jonc lat D'], false),
('Baguette de protection latérale gauche', 'carrosserie', 'protection', ARRAY['jonc lat G'], false),
('Cache boulon de capot', 'carrosserie', 'esthetique', ARRAY['bouchon vis capot'], false),
('Cache écrou de roue', 'carrosserie', 'esthetique', ARRAY['cache boulon'], false),
('Caoutchouc de butée de capot', 'carrosserie', 'protection', ARRAY['tampon capot'], false),
('Caoutchouc de butée de coffre', 'carrosserie', 'protection', ARRAY['tampon coffre'], false),
('Caoutchouc de butée de porte', 'carrosserie', 'protection', ARRAY['tampon porte'], false),
('Contacteur de capot', 'carrosserie', 'securite', ARRAY['switch capot'], false),
('Contacteur de coffre', 'carrosserie', 'securite', ARRAY['switch coffre'], false),
('Hayon arrière', 'carrosserie', 'panneaux', ARRAY['coffre'], true),
('Moteur de coffre électrique', 'carrosserie', 'confort', ARRAY['actionneur coffre'], false),
('Serrure de capot', 'carrosserie', 'serrurerie', ARRAY['gâche capot'], false),
('Support de pare-chocs avant', 'carrosserie', 'fixation', ARRAY['renfort pare-chocs AV'], false),
('Support de pare-chocs arrière', 'carrosserie', 'fixation', ARRAY['renfort pare-chocs AR'], false),
('Tirant de capot', 'carrosserie', 'assistance', ARRAY['compas capot'], false),

-- ========================================
-- ÉCLAIRAGE AVANCÉ (très complet)
-- ========================================
('Ampoule H11', 'eclairage', 'source', ARRAY['lampe H11'], true),
('Ampoule H15', 'eclairage', 'source', ARRAY['lampe H15'], false),
('Ampoule P21W', 'eclairage', 'source', ARRAY['lampe P21W'], true),
('Ampoule PY21W', 'eclairage', 'source', ARRAY['lampe PY21W orange'], true),
('Ampoule R5W', 'eclairage', 'source', ARRAY['lampe R5W'], false),
('Ampoule T10 W5W', 'eclairage', 'source', ARRAY['veilleuse'], true),
('Ballast LED', 'eclairage', 'alimentation', ARRAY['driver LED'], false),
('Capteur de phare adaptatif', 'eclairage', 'regulation', ARRAY['capteur AFS'], false),
('Éclairage de coffre', 'eclairage', 'habitacle', ARRAY['plafonnier coffre'], false),
('Éclairage de boîte à gants', 'eclairage', 'habitacle', ARRAY['lampe vide-poche'], false),
('Feu de gabarit', 'eclairage', 'signalisation', ARRAY['feu de position'], false),
('Lave-phare avant droit', 'eclairage', 'nettoyage', ARRAY['lave-projecteur AV D'], false),
('Lave-phare avant gauche', 'eclairage', 'nettoyage', ARRAY['lave-projecteur AV G'], false),
('Lentille de feu arrière', 'eclairage', 'protection', ARRAY['glace feu AR'], false),
('Module de phare adaptatif', 'eclairage', 'regulation', ARRAY['AFS'], false),
('Moteur de réglage de phare droit', 'eclairage', 'regulation', ARRAY['correcteur phare D'], true),
('Moteur de réglage de phare gauche', 'eclairage', 'regulation', ARRAY['correcteur phare G'], true),
('Plafonnier avant', 'eclairage', 'habitacle', ARRAY['éclairage AV'], true),
('Plafonnier arrière', 'eclairage', 'habitacle', ARRAY['éclairage AR'], false),
('Platine de feu arrière', 'eclairage', 'fixation', ARRAY['support feu AR'], false),
('Pompe de lave-phare', 'eclairage', 'nettoyage', ARRAY['pompe projecteur'], false),
('Projecteur de virage droit', 'eclairage', 'optique', ARRAY['cornering light D'], false),
('Projecteur de virage gauche', 'eclairage', 'optique', ARRAY['cornering light G'], false),
('Réservoir de lave-phare', 'eclairage', 'nettoyage', ARRAY['bocal lave-projecteur'], false),
('Support de phare droit', 'eclairage', 'fixation', ARRAY['fixation phare D'], false),
('Support de phare gauche', 'eclairage', 'fixation', ARRAY['fixation phare G'], false),

-- ========================================
-- NETTOYAGE (ultra complet)
-- ========================================
('Bras d''essuie-glace avant droit', 'electricite', 'nettoyage', ARRAY['bras essuie-glace AV D'], true),
('Bras d''essuie-glace avant gauche', 'electricite', 'nettoyage', ARRAY['bras essuie-glace AV G'], true),
('Bras d''essuie-glace arrière', 'electricite', 'nettoyage', ARRAY['bras essuie-glace AR'], true),
('Buse de lave-glace avant droite', 'electricite', 'nettoyage', ARRAY['gicleur AV D'], false),
('Buse de lave-glace avant gauche', 'electricite', 'nettoyage', ARRAY['gicleur AV G'], false),
('Buse de lave-glace arrière', 'electricite', 'nettoyage', ARRAY['gicleur AR'], false),
('Buse de lave-glace chauffante', 'electricite', 'nettoyage', ARRAY['gicleur chauffant'], false),
('Balai d''essuie-glace avant droit', 'electricite', 'nettoyage', ARRAY['balai AV D'], true),
('Balai d''essuie-glace avant gauche', 'electricite', 'nettoyage', ARRAY['balai AV G'], true),
('Balai d''essuie-glace arrière', 'electricite', 'nettoyage', ARRAY['balai AR'], true),
('Clapet anti-retour lave-glace', 'electricite', 'nettoyage', ARRAY['valve lave-glace'], false),
('Durite de lave-glace', 'electricite', 'nettoyage', ARRAY['tuyau lave-glace'], false),
('Essuie-glace plat', 'electricite', 'nettoyage', ARRAY['balai flat'], true),
('Liquide lave-glace concentré', 'electricite', 'fluide', ARRAY['produit lave-glace'], true),
('Liquide lave-glace hiver', 'electricite', 'fluide', ARRAY['antigel lave-glace'], true),
('Mécanisme d''essuie-glace', 'electricite', 'nettoyage', ARRAY['tringlerie essuie-glace'], false),
('Pompe de lave-glace avant', 'electricite', 'nettoyage', ARRAY['pompe gicleur AV'], true),
('Pompe de lave-glace arrière', 'electricite', 'nettoyage', ARRAY['pompe gicleur AR'], false),
('Réservoir de lave-glace', 'electricite', 'nettoyage', ARRAY['bocal lave-glace'], true),
('Relais d''essuie-glace', 'electricite', 'commande', ARRAY['relais essuie-glace'], false),
('Rotule de bras d''essuie-glace', 'electricite', 'nettoyage', ARRAY['articulation balai'], false),

-- ========================================
-- INSTRUMENTS & AFFICHAGE (complet)
-- ========================================
('Afficheur multifonction', 'electronique', 'affichage', ARRAY['écran LCD'], true),
('Aiguille de compteur', 'electronique', 'affichage', ARRAY['aiguille instrument'], false),
('Cadran de compteur', 'electronique', 'affichage', ARRAY['fond compteur'], false),
('Combiné d''instruments', 'electronique', 'affichage', ARRAY['tableau de bord électronique'], true),
('Compte-tours', 'electronique', 'affichage', ARRAY['tachymètre'], true),
('Compteur de vitesse', 'electronique', 'affichage', ARRAY['speedomètre'], true),
('Écran d''affichage tête haute', 'electronique', 'affichage', ARRAY['HUD'], false),
('Écran tactile central', 'electronique', 'multimedia', ARRAY['écran multimédia'], true),
('Horloge numérique', 'electronique', 'affichage', ARRAY['montre digitale'], false),
('Indicateur de niveau carburant', 'electronique', 'affichage', ARRAY['jauge essence'], true),
('Indicateur de température', 'electronique', 'affichage', ARRAY['thermomètre moteur'], true),
('Jauge de pression d''huile', 'electronique', 'affichage', ARRAY['manomètre huile'], false),
('Rétroéclairage de compteur', 'electronique', 'affichage', ARRAY['éclairage instruments'], false),
('Témoin ABS', 'electronique', 'affichage', ARRAY['voyant ABS'], false),
('Témoin airbag', 'electronique', 'affichage', ARRAY['voyant SRS'], false),
('Témoin de pression pneus', 'electronique', 'affichage', ARRAY['voyant TPMS'], true),
('Témoin moteur', 'electronique', 'affichage', ARRAY['check engine'], true),

-- ========================================
-- VENTILATION & CHAUFFAGE (détaillé)
-- ========================================
('Aérateur central', 'climatisation', 'diffusion', ARRAY['bouche centrale'], false),
('Aérateur latéral droit', 'climatisation', 'diffusion', ARRAY['bouche lat D'], false),
('Aérateur latéral gauche', 'climatisation', 'diffusion', ARRAY['bouche lat G'], false),
('Aérateur de pied avant', 'climatisation', 'diffusion', ARRAY['bouche pied AV'], false),
('Aérateur de pied arrière', 'climatisation', 'diffusion', ARRAY['bouche pied AR'], false),
('Câble de volet de chauffage', 'climatisation', 'commande', ARRAY['câble clapet'], false),
('Canalisation de ventilation', 'climatisation', 'distribution', ARRAY['gaine air'], false),
('Commande de chauffage manuelle', 'climatisation', 'commande', ARRAY['réglage température'], false),
('Résistance chauffage auxiliaire', 'climatisation', 'chauffage', ARRAY['chauffage additionnel'], false),
('Soufflerie de dégivrage', 'climatisation', 'chauffage', ARRAY['ventilation pare-brise'], false),
('Thermostat de chauffage habitacle', 'climatisation', 'regulation', ARRAY['régulateur température'], false),
('Volet de distribution d''air', 'climatisation', 'regulation', ARRAY['clapet répartition'], false),

-- ========================================
-- ALIMENTATION ÉLECTRIQUE (avancé)
-- ========================================
('Batterie auxiliaire', 'electricite', 'stockage', ARRAY['seconde batterie'], false),
('Câble négatif de batterie', 'electricite', 'liaison', ARRAY['câble masse'], true),
('Câble positif de batterie', 'electricite', 'liaison', ARRAY['câble plus'], true),
('Chargeur embarqué', 'electricite', 'charge', ARRAY['onduleur'], false),
('Convertisseur 12V-220V', 'electricite', 'transformation', ARRAY['inverseur'], false),
('Coupe-circuit de batterie', 'electricite', 'protection', ARRAY['cosse coupure'], false),
('Diode de charge', 'electricite', 'regulation', ARRAY['redresseur'], false),
('Porte-fusible', 'electricite', 'protection', ARRAY['support fusible'], false),
('Régulateur de tension', 'electricite', 'regulation', ARRAY['stabilisateur'], false),
('Shunt de batterie', 'electricite', 'mesure', ARRAY['capteur courant'], false),
('Sonde de charge batterie', 'electricite', 'mesure', ARRAY['capteur batterie'], false),

-- ========================================
-- PORTES & FERMETURES (ultra détaillé)
-- ========================================
('Barillet de porte avant gauche', 'carrosserie', 'serrurerie', ARRAY['cylindre porte AV G'], false),
('Barillet de porte avant droite', 'carrosserie', 'serrurerie', ARRAY['cylindre porte AV D'], false),
('Bouchon de serrure', 'carrosserie', 'protection', ARRAY['cache serrure'], false),
('Câble de verrouillage', 'carrosserie', 'serrurerie', ARRAY['tringlerie verrouillage'], false),
('Centralisation électrique', 'carrosserie', 'confort', ARRAY['kit centralisation'], true),
('Gâche de porte avant gauche', 'carrosserie', 'serrurerie', ARRAY['verrou porte AV G'], false),
('Gâche de porte avant droite', 'carrosserie', 'serrurerie', ARRAY['verrou porte AV D'], false),
('Limiteur d''ouverture de porte', 'carrosserie', 'protection', ARRAY['butée porte'], false),
('Mécanisme de porte avant gauche', 'carrosserie', 'serrurerie', ARRAY['mécanisme AV G'], false),
('Mécanisme de porte avant droite', 'carrosserie', 'serrurerie', ARRAY['mécanisme AV D'], false),
('Moteur de verrouillage avant gauche', 'carrosserie', 'confort', ARRAY['actionneur porte AV G'], true),
('Moteur de verrouillage avant droit', 'carrosserie', 'confort', ARRAY['actionneur porte AV D'], true),
('Moteur de verrouillage arrière gauche', 'carrosserie', 'confort', ARRAY['actionneur porte AR G'], false),
('Moteur de verrouillage arrière droit', 'carrosserie', 'confort', ARRAY['actionneur porte AR D'], false),
('Poignée intérieure avant gauche', 'carrosserie', 'commande', ARRAY['poignée int AV G'], false),
('Poignée intérieure avant droite', 'carrosserie', 'commande', ARRAY['poignée int AV D'], false),
('Serrure de porte arrière gauche', 'carrosserie', 'serrurerie', ARRAY['gâche AR G'], false),
('Serrure de porte arrière droite', 'carrosserie', 'serrurerie', ARRAY['gâche AR D'], false),
('Télécommande de porte', 'carrosserie', 'confort', ARRAY['bip centralisation'], true),
('Verrou de sécurité enfant', 'carrosserie', 'securite', ARRAY['sécurité enfant'], false),

-- ========================================
-- CARBURANT & ADDITIFS (complet)
-- ========================================
('Additif AdBlue', 'carburant', 'additif', ARRAY['urée'], true),
('Bouchon AdBlue', 'carburant', 'fermeture', ARRAY['bouchon urée'], false),
('Capteur de carburant', 'carburant', 'mesure', ARRAY['sonde réservoir'], true),
('Cartouche de filtre à gasoil', 'carburant', 'filtration', ARRAY['élément filtrant diesel'], true),
('Conduit de remplissage', 'carburant', 'alimentation', ARRAY['goulotte'], false),
('Durite de retour carburant', 'carburant', 'alimentation', ARRAY['tuyau retour'], false),
('Filtre décanteur diesel', 'carburant', 'filtration', ARRAY['séparateur eau'], false),
('Flotteur de jauge', 'carburant', 'mesure', ARRAY['sonde niveau'], true),
('Pompe de gavage diesel', 'carburant', 'alimentation', ARRAY['pompe basse pression'], false),
('Purgeur de gasoil', 'carburant', 'entretien', ARRAY['vis de purge diesel'], false),
('Réchauffeur de gasoil', 'carburant', 'chauffage', ARRAY['résistance diesel'], false),
('Régulateur de pression carburant', 'carburant', 'regulation', ARRAY['valve pression'], true),
('Tubulure de carburant', 'carburant', 'alimentation', ARRAY['canalisation essence'], false),

-- ========================================
-- DIVERS & SPÉCIFIQUES
-- ========================================
('Adhésif de pare-brise', 'carrosserie', 'etancheite', ARRAY['colle pare-brise'], false),
('Bande anti-crevaison', 'roues', 'protection', ARRAY['mousse anti-crevaison'], false),
('Bidon d''huile 1L', 'moteur', 'fluide', ARRAY['huile 1 litre'], true),
('Bidon d''huile 5L', 'moteur', 'fluide', ARRAY['huile 5 litres'], true),
('Décalque de jante', 'roues', 'decoration', ARRAY['sticker jante'], false),
('Durite de ventilation carter', 'moteur', 'ventilation', ARRAY['tuyau recyclage vapeur'], false),
('Entonnoir de remplissage', 'accessoires', 'entretien', ARRAY['entonnoir huile'], false),
('Film de protection de peinture', 'carrosserie', 'protection', ARRAY['PPF'], false),
('Graisse de roulement', 'suspension', 'lubrification', ARRAY['graisse palier'], false),
('Joint de culasse multicouche', 'moteur', 'etancheite', ARRAY['MLS gasket'], false),
('Kit de distribution complet', 'moteur', 'distribution', ARRAY['kit courroie complet'], true),
('Liquide de frein DOT3', 'freinage', 'fluide', ARRAY['DOT 3'], false),
('Liquide de frein DOT5', 'freinage', 'fluide', ARRAY['DOT 5'], false),
('Nettoyant injecteur', 'carburant', 'entretien', ARRAY['additif nettoyant'], false),
('Pâte à joint', 'moteur', 'etancheite', ARRAY['mastic joints'], false),
('Spray dégrippant', 'accessoires', 'entretien', ARRAY['WD40'], false),
('Spray graisse', 'accessoires', 'entretien', ARRAY['graisse en spray'], false),
('Station de gonflage', 'accessoires', 'entretien', ARRAY['gonfleur pneus'], false)

ON CONFLICT (name) DO NOTHING;

-- Marquer les pièces populaires
UPDATE public.parts
SET is_popular = true
WHERE name IN (
  'Durite de radiateur supérieure',
  'Durite de radiateur inférieure',
  'Liquide de refroidissement',
  'Radiateur d''huile moteur',
  'Radiateur principal',
  'Thermostat d''eau',
  'Ventilateur de radiateur électrique',
  'Carter d''huile aluminium',
  'Filtre à huile cartouche',
  'Filtre à huile vissable',
  'Huile moteur 5W30',
  'Huile moteur 5W40',
  'Huile moteur 10W40',
  'Joint de bouchon de vidange',
  'Boîtier de filtre à air',
  'Débitmètre de masse d''air',
  'Papillon des gaz motorisé',
  'Turbocompresseur complet',
  'Turbocompresseur géométrie variable',
  'Absorbeur de chocs avant',
  'Absorbeur de chocs arrière',
  'Hayon arrière',
  'Ampoule H11',
  'Ampoule P21W',
  'Ampoule PY21W',
  'Ampoule T10 W5W',
  'Moteur de réglage de phare droit',
  'Moteur de réglage de phare gauche',
  'Plafonnier avant',
  'Bras d''essuie-glace avant droit',
  'Bras d''essuie-glace avant gauche',
  'Bras d''essuie-glace arrière',
  'Balai d''essuie-glace avant droit',
  'Balai d''essuie-glace avant gauche',
  'Balai d''essuie-glace arrière',
  'Essuie-glace plat',
  'Liquide lave-glace concentré',
  'Liquide lave-glace hiver',
  'Pompe de lave-glace avant',
  'Réservoir de lave-glace',
  'Combiné d''instruments',
  'Compte-tours',
  'Compteur de vitesse',
  'Écran tactile central',
  'Indicateur de niveau carburant',
  'Indicateur de température',
  'Témoin de pression pneus',
  'Témoin moteur',
  'Câble négatif de batterie',
  'Câble positif de batterie',
  'Centralisation électrique',
  'Moteur de verrouillage avant gauche',
  'Moteur de verrouillage avant droit',
  'Télécommande de porte',
  'Additif AdBlue',
  'Capteur de carburant',
  'Cartouche de filtre à gasoil',
  'Flotteur de jauge',
  'Régulateur de pression carburant',
  'Bidon d''huile 1L',
  'Bidon d''huile 5L',
  'Kit de distribution complet'
);
