-- Ajout complet des pièces moteur et admission/échappement manquantes

-- ========================================
-- MOTEUR COMPLET (toutes les pièces internes)
-- ========================================
INSERT INTO public.parts (name, category, subcategory, synonyms, is_popular) VALUES
('Moteur complet', 'moteur', 'ensemble', ARRAY['bloc moteur complet'], true),
('Bloc moteur', 'moteur', 'structure', ARRAY['bloc cylindres'], true),
('Culasse', 'moteur', 'structure', ARRAY['tête de moteur'], true),
('Joint de culasse', 'moteur', 'etancheite', ARRAY['joint de tête'], true),
('Couvre-culasse', 'moteur', 'protection', ARRAY['cache culasse'], true),
('Arbre à cames admission', 'moteur', 'distribution', ARRAY['AAC admission'], true),
('Arbre à cames échappement', 'moteur', 'distribution', ARRAY['AAC échappement'], true),
('Poussoirs hydrauliques', 'moteur', 'distribution', ARRAY['hydraulic lifters'], false),
('Soupapes admission', 'moteur', 'distribution', ARRAY['soupapes entrée'], false),
('Soupapes échappement', 'moteur', 'distribution', ARRAY['soupapes sortie'], false),
('Sièges de soupapes', 'moteur', 'distribution', ARRAY['portées soupapes'], false),
('Ressorts de soupapes', 'moteur', 'distribution', ARRAY['ressorts AAC'], false),
('Coupelles de ressort soupapes', 'moteur', 'distribution', ARRAY['siège ressort'], false),
('Clavettes de soupapes', 'moteur', 'distribution', ARRAY['demi-lunes'], false),
('Arbre intermédiaire', 'moteur', 'mecanique', ARRAY['arbre équilibreur'], false),
('Vilebrequin', 'moteur', 'mecanique', ARRAY['vilo'], true),
('Paliers de vilebrequin', 'moteur', 'mecanique', ARRAY['coussinets vilo'], false),
('Coussinets de bielle', 'moteur', 'mecanique', ARRAY['paliers bielles'], false),
('Bielles', 'moteur', 'mecanique', ARRAY['connecting rods'], true),
('Pistons', 'moteur', 'mecanique', ARRAY['pistons moteur'], true),
('Segments de piston', 'moteur', 'etancheite', ARRAY['anneaux piston'], true),
('Segments racleur', 'moteur', 'etancheite', ARRAY['segments huile'], false),
('Axe de piston', 'moteur', 'mecanique', ARRAY['maneton piston'], false),
('Circlips de piston', 'moteur', 'fixation', ARRAY['clips axe piston'], false),
('Carter moteur inférieur', 'moteur', 'structure', ARRAY['carter huile'], true),
('Carter moteur supérieur', 'moteur', 'structure', ARRAY['bloc moteur bas'], false),
('Bouchon de vidange', 'moteur', 'entretien', ARRAY['vis vidange'], true),
('Bouchon de remplissage huile', 'moteur', 'entretien', ARRAY['bouchon huile'], true),
('Volant moteur', 'moteur', 'transmission', ARRAY['volant d''inertie'], true),
('Volant moteur bi-masse', 'moteur', 'transmission', ARRAY['DMF'], true),
('Couronne de démarreur', 'moteur', 'demarrage', ARRAY['couronne volant'], false),
('Damper poulie vilebrequin', 'moteur', 'distribution', ARRAY['poulie harmonique'], false),
('Support moteur gauche', 'moteur', 'fixation', ARRAY['silent-bloc moteur G'], true),
('Support moteur droit', 'moteur', 'fixation', ARRAY['silent-bloc moteur D'], true),
('Support moteur arrière', 'moteur', 'fixation', ARRAY['silent-bloc moteur AR'], true),
('Support moteur avant', 'moteur', 'fixation', ARRAY['silent-bloc moteur AV'], false),
('Silentblocs moteur kit', 'moteur', 'fixation', ARRAY['kit supports moteur'], true),
('Capteur PMH', 'moteur', 'mesure', ARRAY['capteur régime moteur'], true),
('Capteur position AAC', 'moteur', 'mesure', ARRAY['capteur arbre à cames'], true),
('Capteur pression huile', 'moteur', 'mesure', ARRAY['manocontact'], true),
('Capteur température eau', 'moteur', 'mesure', ARRAY['sonde température moteur'], true),
('Capteur cliquetis', 'moteur', 'mesure', ARRAY['knock sensor'], false),

-- ========================================
-- ADMISSION / ÉCHAPPEMENT (ultra complet)
-- ========================================
('Collecteur d''admission', 'moteur', 'admission', ARRAY['manifold admission'], true),
('Joint collecteur admission', 'moteur', 'etancheite', ARRAY['joint manifold admission'], true),
('Joint de collecteur échappement', 'moteur', 'etancheite', ARRAY['joint manifold échappement'], true),
('Turbo turbocompresseur', 'moteur', 'suralimentation', ARRAY['turbo'], true),
('Turbocompresseur neuf', 'moteur', 'suralimentation', ARRAY['turbo neuf'], true),
('Turbocompresseur échange standard', 'moteur', 'suralimentation', ARRAY['turbo reconditionné'], true),
('Wastegate soupape de décharge', 'moteur', 'turbo', ARRAY['valve wastegate'], false),
('Actuateur de wastegate', 'moteur', 'turbo', ARRAY['capsule wastegate'], false),
('Durite de turbo haute pression', 'moteur', 'turbo', ARRAY['tuyau turbo HP'], true),
('Durite de turbo basse pression', 'moteur', 'turbo', ARRAY['tuyau turbo BP'], false),
('Durite intercooler admission', 'moteur', 'turbo', ARRAY['durite échangeur entrée'], false),
('Durite intercooler sortie', 'moteur', 'turbo', ARRAY['durite échangeur sortie'], false),
('Intercooler échangeur', 'moteur', 'refroidissement', ARRAY['radiateur air turbo'], true),
('Tuyauterie intercooler', 'moteur', 'turbo', ARRAY['tubulure intercooler'], false),
('Filtre à air', 'moteur', 'admission', ARRAY['cartouche air'], true),
('Filtre à air sport', 'moteur', 'admission', ARRAY['filtre KN'], false),
('Boîtier filtre à air', 'moteur', 'admission', ARRAY['boîte à air'], true),
('Couvercle boîtier air', 'moteur', 'admission', ARRAY['couvercle filtre'], false),
('Débitmètre d''air MAF', 'moteur', 'mesure', ARRAY['mass airflow sensor'], true),
('Capteur de pression admission MAP', 'moteur', 'mesure', ARRAY['manifold pressure'], true),
('Papillon des gaz', 'moteur', 'admission', ARRAY['throttle body'], true),
('Boîtier papillon motorisé', 'moteur', 'admission', ARRAY['papillon électronique'], true),
('Soupape EGR', 'moteur', 'antipollution', ARRAY['valve EGR'], true),
('Refroidisseur EGR', 'moteur', 'antipollution', ARRAY['radiateur EGR'], true),
('Joint de vanne EGR', 'moteur', 'etancheite', ARRAY['joint EGR'], false),
('Vanne de ralenti', 'moteur', 'admission', ARRAY['IAC valve'], false),
('Tuyau échappement avant', 'echappement', 'evacuation', ARRAY['tube avant'], true),
('Catalyseur', 'echappement', 'depollution', ARRAY['pot catalytique'], true),
('Catalyseur sport', 'echappement', 'performance', ARRAY['cata 200 cellules'], false),
('FAP filtre à particules', 'echappement', 'depollution', ARRAY['DPF'], true),
('Additif FAP', 'echappement', 'entretien', ARRAY['cérine FAP'], false),
('Sonde lambda avant', 'echappement', 'mesure', ARRAY['sonde O2 pré-cata'], true),
('Sonde lambda arrière', 'echappement', 'mesure', ARRAY['sonde O2 post-cata'], true),
('Sonde lambda universel', 'echappement', 'mesure', ARRAY['sonde O2 générique'], false),
('Sonde de température échappement', 'echappement', 'mesure', ARRAY['capteur température gaz'], false),
('Capteur de pression différentielle FAP', 'echappement', 'mesure', ARRAY['capteur pression FAP'], false),
('Silencieux intermédiaire', 'echappement', 'acoustique', ARRAY['pot central'], true),
('Silencieux arrière', 'echappement', 'acoustique', ARRAY['pot arrière'], true),
('Silencieux avant', 'echappement', 'acoustique', ARRAY['pot avant'], false),
('Embout échappement', 'echappement', 'sortie', ARRAY['sortie échappement'], true),
('Embout chromé', 'echappement', 'esthetique', ARRAY['sortie chromée'], false),
('Embout double', 'echappement', 'esthetique', ARRAY['sorties doubles'], false),
('Ligne complète échappement', 'echappement', 'systeme', ARRAY['échappement complet'], true),
('Ligne sport échappement', 'echappement', 'performance', ARRAY['échappement performance'], false),
('Collecteur échappement 4-2-1', 'echappement', 'performance', ARRAY['header 4-2-1'], false),
('Collecteur échappement 4-1', 'echappement', 'performance', ARRAY['header 4-1'], false),
('Downpipe turbo', 'echappement', 'turbo', ARRAY['tube descente turbo'], false),
('Downpipe sport', 'echappement', 'performance', ARRAY['downpipe sans cata'], false),
('Bride échappement', 'echappement', 'fixation', ARRAY['collier échappement'], false),
('Collier échappement', 'echappement', 'fixation', ARRAY['collier serrage'], false),
('Joint échappement métal', 'echappement', 'etancheite', ARRAY['joint collecteur'], false),
('Joint échappement graphite', 'echappement', 'etancheite', ARRAY['joint graphité'], false),
('Support échappement', 'echappement', 'fixation', ARRAY['silent-bloc échappement'], false),
('Suspente échappement', 'echappement', 'fixation', ARRAY['tampon échappement'], false),
('Manchon réparation échappement', 'echappement', 'reparation', ARRAY['manchon soudure'], false),
('Pâte échappement', 'echappement', 'reparation', ARRAY['mastic échappement'], false),

-- ========================================
-- INJECTION ET ALIMENTATION CARBURANT
-- ========================================
('Injecteur essence', 'carburant', 'injection', ARRAY['injecteur'], true),
('Injecteur diesel', 'carburant', 'injection', ARRAY['injecteur gasoil'], true),
('Injecteur pompe', 'carburant', 'injection', ARRAY['injecteur-pompe'], false),
('Rampe d''injection essence', 'carburant', 'distribution', ARRAY['rail injection essence'], true),
('Rampe d''injection diesel', 'carburant', 'distribution', ARRAY['common rail'], true),
('Capteur de pression rampe', 'carburant', 'mesure', ARRAY['capteur rail'], false),
('Régulateur pression carburant', 'carburant', 'regulation', ARRAY['régulateur pression'], true),
('Pompe haute pression diesel', 'carburant', 'injection', ARRAY['pompe HP gasoil'], true),
('Pompe à essence', 'carburant', 'alimentation', ARRAY['pompe carburant'], true),
('Pompe à essence immergée', 'carburant', 'alimentation', ARRAY['pompe in-tank'], true),
('Pompe de gavage diesel', 'carburant', 'alimentation', ARRAY['pompe lift'], false),
('Filtre à essence', 'carburant', 'filtration', ARRAY['filtre carburant essence'], true),
('Filtre à gasoil', 'carburant', 'filtration', ARRAY['filtre carburant diesel'], true),
('Filtre décanteur', 'carburant', 'filtration', ARRAY['séparateur eau'], false),
('Capteur niveau carburant', 'carburant', 'mesure', ARRAY['jauge essence'], true),
('Flotteur carburant', 'carburant', 'mesure', ARRAY['flotteur réservoir'], false),
('Bouchon réservoir', 'carburant', 'fermeture', ARRAY['bouchon essence'], true),
('Trappe à carburant', 'carburant', 'acces', ARRAY['trappe essence'], true),
('Réservoir carburant', 'carburant', 'stockage', ARRAY['réservoir essence'], true),
('Durite carburant', 'carburant', 'alimentation', ARRAY['tuyau essence'], false),
('Tuyau rigide carburant', 'carburant', 'alimentation', ARRAY['canalisation carburant'], false),
('Clapet anti-retour carburant', 'carburant', 'regulation', ARRAY['valve anti-retour'], false),
('Pot à charbon actif', 'carburant', 'antipollution', ARRAY['canister'], false),
('Électrovanne purge canister', 'carburant', 'antipollution', ARRAY['valve purge vapeur'], false),

-- ========================================
-- ALLUMAGE ET GESTION MOTEUR
-- ========================================
('Bougie d''allumage', 'electricite', 'allumage', ARRAY['spark plug'], true),
('Bougie de préchauffage', 'electricite', 'demarrage', ARRAY['bougie diesel'], true),
('Bobine d''allumage', 'electricite', 'allumage', ARRAY['coil'], true),
('Bobine crayon', 'electricite', 'allumage', ARRAY['bobine individuelle'], true),
('Câbles de bougies', 'electricite', 'allumage', ARRAY['fils haute tension'], true),
('Faisceau allumage', 'electricite', 'allumage', ARRAY['kit câbles bougies'], false),
('Relais de préchauffage', 'electricite', 'demarrage', ARRAY['boîtier préchauffage'], false),
('Calculateur moteur', 'electronique', 'gestion moteur', ARRAY['ECU'], true),
('Calculateur injection', 'electronique', 'gestion moteur', ARRAY['boîtier injection'], true),
('Faisceau moteur', 'electricite', 'cablage', ARRAY['câblage moteur'], true),
('Faisceau injection', 'electricite', 'cablage', ARRAY['câblage injecteurs'], false),
('Connecteur injecteur', 'electricite', 'connexion', ARRAY['prise injecteur'], false),
('Pédale d''accélérateur', 'electronique', 'commande', ARRAY['pédale électronique'], true),
('Potentiomètre pédale', 'electronique', 'mesure', ARRAY['capteur pédale'], false)

ON CONFLICT (name) DO NOTHING;

-- Marquer les pièces populaires
UPDATE public.parts
SET is_popular = true
WHERE name IN (
  'Moteur complet',
  'Bloc moteur',
  'Culasse',
  'Joint de culasse',
  'Couvre-culasse',
  'Arbre à cames admission',
  'Arbre à cames échappement',
  'Vilebrequin',
  'Bielles',
  'Pistons',
  'Segments de piston',
  'Carter moteur inférieur',
  'Bouchon de vidange',
  'Bouchon de remplissage huile',
  'Volant moteur',
  'Volant moteur bi-masse',
  'Support moteur gauche',
  'Support moteur droit',
  'Support moteur arrière',
  'Silentblocs moteur kit',
  'Capteur PMH',
  'Capteur position AAC',
  'Capteur pression huile',
  'Capteur température eau',
  'Collecteur d''admission',
  'Joint collecteur admission',
  'Joint de collecteur échappement',
  'Turbo turbocompresseur',
  'Turbocompresseur neuf',
  'Turbocompresseur échange standard',
  'Durite de turbo haute pression',
  'Intercooler échangeur',
  'Filtre à air',
  'Boîtier filtre à air',
  'Débitmètre d''air MAF',
  'Capteur de pression admission MAP',
  'Papillon des gaz',
  'Boîtier papillon motorisé',
  'Soupape EGR',
  'Refroidisseur EGR',
  'Tuyau échappement avant',
  'Catalyseur',
  'FAP filtre à particules',
  'Sonde lambda avant',
  'Sonde lambda arrière',
  'Silencieux intermédiaire',
  'Silencieux arrière',
  'Embout échappement',
  'Ligne complète échappement',
  'Injecteur essence',
  'Injecteur diesel',
  'Rampe d''injection essence',
  'Rampe d''injection diesel',
  'Régulateur pression carburant',
  'Pompe haute pression diesel',
  'Pompe à essence',
  'Pompe à essence immergée',
  'Filtre à essence',
  'Filtre à gasoil',
  'Capteur niveau carburant',
  'Bouchon réservoir',
  'Trappe à carburant',
  'Réservoir carburant',
  'Bougie d''allumage',
  'Bougie de préchauffage',
  'Bobine d''allumage',
  'Bobine crayon',
  'Câbles de bougies',
  'Calculateur moteur',
  'Calculateur injection',
  'Faisceau moteur',
  'Pédale d''accélérateur'
);
