-- Ajout des pièces performance, tuning et modification

-- ========================================
-- PERFORMANCE & TUNING
-- ========================================
INSERT INTO public.parts (name, category, subcategory, synonyms, is_popular) VALUES
('Turbo grande taille', 'moteur', 'performance', ARRAY['big turbo', 'turbo upgrade'], false),
('Kit turbo', 'moteur', 'performance', ARRAY['turbo kit complet'], false),
('Wastegate externe', 'moteur', 'performance', ARRAY['wastegate aftermarket'], false),
('Blow-off valve', 'moteur', 'performance', ARRAY['BOV', 'dump valve'], false),
('Admission direct air froid', 'moteur', 'performance', ARRAY['cold air intake'], false),
('Filtre à air coton', 'moteur', 'performance', ARRAY['filtre sport'], false),
('Intercooler sport', 'moteur', 'performance', ARRAY['échangeur renforcé'], false),
('Downpipe décatalysé', 'echappement', 'performance', ARRAY['downpipe sans cata'], false),
('Échappement inox sport', 'echappement', 'performance', ARRAY['ligne inox'], false),
('Échappement titane', 'echappement', 'performance', ARRAY['ligne titane'], false),
('Collecteur 4-2-1 inox', 'echappement', 'performance', ARRAY['header performance'], false),
('Valve d''échappement active', 'echappement', 'performance', ARRAY['échappement à clapets'], false),
('Kit éthanol E85', 'carburant', 'modification', ARRAY['conversion bioéthanol'], false),
('Boîtier additionnel', 'electronique', 'performance', ARRAY['chip tuning box'], false),
('Calculateur reprogrammé stage 1', 'electronique', 'performance', ARRAY['ECU stage 1'], false),
('Calculateur reprogrammé stage 2', 'electronique', 'performance', ARRAY['ECU stage 2'], false),
('Calculateur reprogrammé stage 3', 'electronique', 'performance', ARRAY['ECU stage 3'], false),
('Kit embrayage renforcé', 'transmission', 'performance', ARRAY['embrayage sport'], false),
('Volant moteur allégé', 'moteur', 'performance', ARRAY['flywheel léger'], false),
('Différentiel à glissement limité', 'transmission', 'performance', ARRAY['LSD'], false),
('Cardan renforcé', 'transmission', 'performance', ARRAY['cardan HD'], false),
('Kit freins sport avant', 'freinage', 'performance', ARRAY['big brake kit AV'], false),
('Kit freins sport arrière', 'freinage', 'performance', ARRAY['big brake kit AR'], false),
('Disques carbone céramique', 'freinage', 'performance', ARRAY['disques CCB'], false),
('Plaquettes racing', 'freinage', 'performance', ARRAY['plaquettes piste'], false),
('Durites aviation freinage', 'freinage', 'performance', ARRAY['durites tressées'], false),
('Amortisseurs sport réglables', 'suspension', 'performance', ARRAY['amortisseurs coilovers'], false),
('Kit combinés filetés', 'suspension', 'performance', ARRAY['coilovers'], false),
('Ressorts courts', 'suspension', 'performance', ARRAY['ressorts sport'], false),
('Barre anti-roulis renforcée', 'suspension', 'performance', ARRAY['stabilisatrice HD'], false),
('Silent-blocs polyuréthane', 'suspension', 'performance', ARRAY['silent-blocs PU'], false),
('Kit géométrie réglable', 'suspension', 'performance', ARRAY['bras réglables'], false),
('Jantes forgées', 'roues', 'performance', ARRAY['jantes forgées alu'], false),
('Pneumatiques semi-slick', 'roues', 'performance', ARRAY['pneus sport'], false),
('Kit écrous de roue titane', 'roues', 'performance', ARRAY['écrous Ti'], false),
('Rétroviseurs carbone', 'carrosserie', 'esthetique', ARRAY['coques carbone'], false),
('Becquet carbone', 'carrosserie', 'aero', ARRAY['aileron carbone'], false),
('Splitter avant carbone', 'carrosserie', 'aero', ARRAY['lame avant carbone'], false),
('Diffuseur arrière', 'carrosserie', 'aero', ARRAY['diffuseur carbone'], false),
('Capot carbone', 'carrosserie', 'allègement', ARRAY['bonnet carbone'], false),
('Portes carbone', 'carrosserie', 'allègement', ARRAY['portes carbone'], false),
('Hayon carbone', 'carrosserie', 'allègement', ARRAY['coffre carbone'], false),
('Vitres polycarbonate', 'vitrage', 'allègement', ARRAY['vitres lexan'], false),
('Harnais 4 points', 'interieur', 'securite', ARRAY['ceinture 4 points'], false),
('Harnais 6 points', 'interieur', 'securite', ARRAY['ceinture 6 points'], false),
('Arceau de sécurité', 'interieur', 'securite', ARRAY['roll cage'], false),
('Volant sport', 'interieur', 'performance', ARRAY['volant racing'], false),
('Pédalier aluminium', 'interieur', 'esthetique', ARRAY['pédales alu'], false),
('Manomètre boost', 'interieur', 'mesure', ARRAY['mano turbo'], false),
('Manomètre pression huile', 'interieur', 'mesure', ARRAY['mano huile'], false),
('Manomètre température eau', 'interieur', 'mesure', ARRAY['mano eau'], false),
('Kit strip intérieur', 'interieur', 'allègement', ARRAY['allègement habitacle'], false),
('Sièges baquets', 'interieur', 'performance', ARRAY['sièges baquet'], false),
('Support de boîte renforcé', 'transmission', 'performance', ARRAY['support BV HD'], false),
('Kit distribution renforcé', 'moteur', 'performance', ARRAY['kit timing HD'], false)

ON CONFLICT (name) DO NOTHING;
